react-native-cli/index.js

**react-native-cli/index.js**
- change double to single quotes

Lint code - change double to single quotes to keep code style

---

docs/Tutorial.md

Removes typo from tutorial, I don't think `gr` is supposed to be present.

remove extraneous word

---

website/jsdocs/TypeExpressionParser.js
website/jsdocs/findExportDefinition.js
website/jsdocs/generic-function-visitor.js
website/jsdocs/jsdocs.js
website/jsdocs/meta.js
website/jsdocs/traverseFlat.js
website/jsdocs/type.js

Lint code, change double to single quotes where applicable. Add/Remove semicolons where needed to reflect code style.
**website/jsdocs/**

Lint code - change double quotes to single in website/jsdocs

---

docs/GettingStarted.md

In getting started, it asks if you are new to node and npm, but there are no links to explain what either is. I believe these links help to clarify.
Previously: 
Proposed change:

Add links to node and npm in Requirements

---

package.json
packager/package.json

We should separate out the packages but for now we this is a quick fix

Use only one package for dependencies, for now. Fixes #225

---

website/server/server.js

I think that would be a good promises apply. Even for more complex tasks. What do you think?
I started developing locally using [bluebird](https://github.com/petkaantonov/bluebird) to "promisify" all functions. For now, I just sent half PR, without promises part. If agree, I'll add promises feature.

Support/use Promises 

---

react-native-cli/index.js

Before:
> Command `foo` unrecognized.Did you mean to run this inside a react-native project?
After:
> Command `foo` unrecognized. Did you mean to run this inside a react-native project?

Adds missing space character to CLI error message

---

docs/Debugging.md
docs/NativeModulesIOS.md
website/src/react-native/index.js

I wasn't sure how a PR for a gh-page should be made. I kept it simple and just changed the files that generate the final website changes. I did not commit any generated files.

Add basic documentation for debugging react native apps

---

docs/Debugging.md

Add a comment about Live Reload

---

docs/NativeModulesIOS.md

The correct path is 'linking-libraries' as seen on https://raw.githubusercontent.com/facebook/react-native/master/docs/Libraries.md.

Fix "next" link on NativeModules doc

---

React.podspec

We still write to NSLog or similar as well
There may be some performance penalty but I don't think so unless the REPL
window is open. It would not be hard to add a flag to this if necessary.
This will definitely make debugging and development easier.

Making console write to the Safari debugger console as well as NSLog

---

docs/GettingStarted.md
docs/Troubleshooting.md

Closes my issue at https://github.com/facebook/react-native/issues/306

Add Troubleshooting doc for recurring issues

---

docs/Debugging.md

Header for Live Reload section had a period after it. Other headers didn't- now it doesn't either.

(fix typo) Debugging.md

---

docs/NativeModulesIOS.md

The example omitted the `#import "RCTBridge.h"`, which will lead to CE.

Add import RCTBridge.h for event sending example

---

docs/EmbeddedApp.md

- [*Rendered docs from branch*](https://github.com/facebook/react-native/blob/1c3dd29c92ef884192a773135aecbf596db34509/docs/EmbeddedApp.md)
- [*Rich text diff*](https://github.com/facebook/react-native/compare/master...andrewsardone:aps-embedded-app?expand=1&name=aps-embedded-app&short_path=b46baeb#diff-b46baeb88ade3cb68ee43248a024d34c)
This builds off of the awesome work from @tjwudi to expand on the embedded app docs when using @cocoapods.
- **main change**: instructs user to create their React JavaScript in a top-level `ReactComponent` directory as a sibling of their existing app code, and *not* in the `Pods/` directory where third-party dependencies are installed
- [Relevant commit](https://github.com/facebook/react-native/commit/f3ddef0ff3ee906b359987108b4f8266cb3f35b9)
- I think …

Improve EmbeddedApp.md docs wrt location of ReactComponent (also minor formatting)

---

docs/LinkingLibraries.md

some small tweaks to the Linking Libraries docs

language fixes

---

Examples/SampleApp/index.ios.js
Examples/UIExplorer/UIExplorerPage.js
Libraries/Components/MapView/MapView.js
Libraries/Components/ScrollView/ScrollView.js
Libraries/Components/WebView/WebView.ios.js
Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js
Libraries/ReactIOS/ReactIOS.js
Libraries/ReactIOS/ReactIOSDefaultInjection.js
Libraries/ReactIOS/ReactIOSMount.js
React.podspec
React/Modules/RCTAsyncLocalStorage.m
React/Modules/RCTUIManager.m
React/Views/RCTViewManager.m
React/Views/RCTWebView.m
React/Views/RCTWebViewManager.m
package.json
packager/debugger.html
packager/react-packager/src/DependencyResolver/haste/DependencyGraph/__tests__/DependencyGraph-test.js
packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js
packager/react-packager/src/DependencyResolver/haste/__tests__/HasteDependencyResolver-test.js
packager/react-packager/src/DependencyResolver/haste/index.js
packager/react-packager/src/DependencyResolver/haste/requirePattern.js

- Bugfix/require module regexp | Amjad Masad
- [ReactNative] RCTView's shadowOffset is of float type, not CGFloat | Kevin Gozali
- Fix WebView automaticallyAdjustContentInsets error | Spencer Ahrens
- [react-native] map view - add onTouch** props | Jiajie Zhu
- [react-native] Fix documentation extraction for View | Ben Alpert
- [ReactNative] Add few hints in the UI | Alex Kotliarskyi
- Adding `scrollWithoutAnimationTo` method for ScrollViews | Felix Oghina
- [ScrollView] Add "bounces" property to ScrollView propTypes | Spencer Ahrens
- Fix a crash in RCTAsyncLocalStorage when the value is not a string. | Spencer Ahrens
- [ReactNative] Remove global MutationObserver to fix Bluebird feature detection | Christopher Chedeau
- [catalyst] fix typo | Jiajie Zhu
- [react-packager] check-in …

Updates from Tue 31 Mar

---

React/Views/RCTWebViewManager.m

WebView component's automaticallyAdjustContentInsets prop should be type BOOL. Fixes #251.

Fix WebView automaticallyAdjustContentInsets error

---

packager/README.md

-fix a few typos
-edit grammar on a few sentences, adding punctuation or keeping tense consistent
-make capitalization consistent in ReactPackager.middleware(options) section

(cleanup/ fix grammer & typos) packager/README.md

---

docs/Style.md

Add links to source code that shows supported CSS properties. It will be painful if we don't know what is supported.
Given that CSS properties support may be ever changing, I decided to document links to source code directly.

Document supported CSS properties

---

docs/EmbeddedApp.md

Original link to image for EmbeddedAppContainerViewExample.png failed. Fixed link to load same image. Did not touch source code.

Fixed broken image link

---

docs/EmbeddedApp.md

Image link for EmbeddedAppExample.png failed to load. Fixed link to load original image. Did not touch source code.

Fixed broken image link for EmbeddedAppExample.png

---

docs/LinkingLibraries.md

AddToSearchPaths.png failed to load properly. Fixed link to load same image from "react-native/website/src/react-native/img". Did not touch source code.

Fixed image link for AddToSearchPaths.png

---

docs/LinkingLibraries.md

Image for AddToBuildPhases.png failed to load. Fixed link to load same image from "react-native/website/src/react-native/img". Did not touch source code.

Fixed broken image for AddToBuildPhases.png

---

React/React.xcodeproj/project.pbxproj
packager/README.md
packager/packager.js
packager/react-packager/src/DependencyResolver/haste/polyfills/require.js

- Packager status page & build validating against it. | Spencer Ahrens
- Do not expose define references in require polyfill | Amjad Masad

Updates from Wed 1 Apr

---

website/package.json
website/server/generate.js

This will prevent us from having pages on the site that just show error
stack traces -- instead, Travis will fail with an error and we'll
notice sooner.
I cleaned up this logic to use promises which was way easier to track
for the error behavior and should be simpler to follow regardless.

Fail generating website if any page throws an error

---

.travis.yml

Now website build failures should fail the build, and Xcode tests should
run correctly (previously they didn't seem to be -- Travis was
complaining that no project or scheme was specified).

Redo Travis config

---

website/server/generate.js

So Travis won't wipe out the website on error. :\

Die with status 1 when website generation fails

---

docs/RunningOnDevice.md
docs/Testing.md

Simple guide about running RN apps on device. Closes #240 
cc @vjeux @spicyj @brentvatne

Add docs about running on device

---

docs/GettingStarted.md

Updated the docs for installing watchman with --HEAD per @wez suggestion in this issue thread https://github.com/facebook/react-native/issues/239

(update) Install watchman w/ --HEAD to avoid error

---

docs/EmbeddedApp.md

It cannot see the some images that are using absolute path on the [web page](http://facebook.github.io/react-native/docs/embeded-app.html#content),
so I think it should use absolute path.

Fixed #632 using relative path instead of absolute path for Image tag

---

docs/EmbeddedApp.md
docs/RunningOnDevice.md

- Fixed a typo.
- Fixed **Next →** link at GUIDES Running On Device.

Fix typo and broken link.

---

Examples/UIExplorer/Navigator/JumpingNavSample.js
Examples/UIExplorer/TabBarIOSExample.js
Libraries/Components/ScrollResponder.js
Libraries/Components/TabBarIOS/TabBarIOS.ios.js
Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js
Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js
Libraries/RCTTest/RCTTestModule.h
Libraries/RCTTest/RCTTestRunner.m
Libraries/RCTWebSocketDebugger/RCTWebSocketExecutor.m
Libraries/ReactIOS/ReactIOSDefaultInjection.js
React/Base/RCTBridge.h
React/Base/RCTBridge.m
React/Base/RCTConvert.m
React/Base/RCTDevMenu.h
React/Base/RCTDevMenu.m
React/Base/RCTJavaScriptLoader.h
React/Base/RCTJavaScriptLoader.m
React/Base/RCTRootView.h
React/Base/RCTRootView.m
React/Executors/RCTContextExecutor.h
React/Modules/RCTUIManager.h
React/Modules/RCTUIManager.m
React/React.xcodeproj/project.pbxproj
React/Views/RCTTabBarItem.m
React/Views/RCTView.m
package.json
packager/packager.js
packager/react-packager/src/FileWatcher/index.js

- Update deps order - core modules first | Amjad Masad
- [ReactNative] Workaround double cmd+r bug | Christopher Chedeau
- [react-native] Nicer error for undefined or string tag names | Ben Alpert
- [ReactNative] Fix script load from local files | Tadeu Zagallo
- [react_native] JS files from D1961099: Format stack trace on native side | Alex Kotliarskyi
- [ReactNative] Cleanup TabBar and its example | Christopher Chedeau
- [ReactNative] Allow recover from debugger error | Tadeu Zagallo
- [react-native] Update react to 0.13.1, jstransform alongside | Ben Alpert
- Fixed tap-to-zoom in Groups photo viewer | Sumeet Vaidya
- Fix hitTest for auto | Tadeu Zagallo
- [ReactNative] Unfork RKRootView | Tadeu Zagallo
- [react-packager] Ignore dotfiles in file watching | Amjad Masad

Updates from Fri 3 Apr

---

website/publish.sh

This was causing the build to fail if the website hadn't changed,
because `git commit` would exit 1. This matches what we do on React now.

Don't try to commit website on Travis if no changes

---

css/react-native.css

See the page: http://facebook.github.io/react-native/docs/image.html#content

Fix docs->image width over 100%，avoid scroll-x

---

cli.js
local-cli/cli.js
local-cli/install.js
package.json
react-native-cli/index.js

This moves the local cli to the local-cli directory.
Then it creates an install command in the local cli to find all react native components that are extensions through npm. The found modules are installed through cocoapods.

Created install command and moved cli to local-cli directory

---

docs/Debugging.md

Added a hint about how to enable debugging on real devices.

Debugging on real devices

---

local-cli/wrong-react-native.js
package.json

This adds a react-native binary that just output some instructions.

Warn when installing globally react-native instead of react-native-cli

---

React/React.xcodeproj/project.pbxproj

Due to a curl bug, `curl localhost` doesn't work if there's an IPv6 entry in `/etc/hosts` (I believe OSX Yosemite has this by default).
Say you've run `npm start` manually. When you run your project from XCode the build will fail citing:
```
Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!
Port 8081 already in use, packager is either not running or not running correctly
```
On any subsequent compile you must quit the packager first before compilation to avoid the compile time error (PITA).
There is only one packager instance running, but the script fails to detect the instance properly. Another possible solution (instead of forcing IPv4 mode) would be to use `0.0.0.0` in place of `localhost`.

Force curl to use IPv4

---

README.md
docs/NativeModulesIOS.md
website/src/react-native/index.js

To reflect deprecation of `RCT_EXPORT` in favour of `RCT_EXPORT_METHOD`

Fix bridge docs for `RCT_EXPORT`

---

CONTRIBUTING.md

Someone on IRC mentioned the Facebook community for React Native, but I don't
see it mentioned in any of the docs.

Add a link to the Facebook community

---

.travis.yml
scripts/.gitignore
scripts/e2e-npmrc
scripts/e2e-sinopia.config.yml
scripts/e2e-test.sh

The idea is to create a test that makes sure our npm publishing and `react-native init` workflow is smooth.

Add end-to-end test

---

docs/NativeModulesIOS.md

Described how JS method names are derived from Obj-C selectors and mention RCT_REMAP_METHOD.

[Docs] Add note about JS names for exported methods and RCT_REMAP_METHOD

---

.gitignore
Examples/SampleApp/_flowconfig
Examples/SampleApp/_gitignore
init.sh
scripts/e2e-test.sh

Added `.flowconfig` template (and a test for it!)
Test Plan:
```
$ ./scripts/e2e-test.sh
```

Add flowconfig to SampleApp

---

docs/NativeModulesIOS.md

Simple fix - GitHub's markdown is processed differently than Jekyll's, so just fixing things up to look better.

[Docs] Fix formatting for "JavaScript method names" section in docs

---

Examples/SampleApp/iOS/AppDelegate.m
docs/RunningOnDevice.md
local-cli/bundle.js
local-cli/cli.js

This is an initial stab at creating a node-based bundling script so that you don't have to manually run `curl`. My idea was to have it as a command under `react-native`. It allows command line flags for `dev` and `minify`. It still requires the server to be up, but I hope to detect that and maybe automatically run the server in the future.
Wondering if this is a good idea and if so, the right approach.

Bundle script instead of curl

---

CONTRIBUTING.md

@nicklockwood @a2 @vjeux Want to add something else? (or remove something)

Add some common objc nits to the style guide

---

Libraries/Components/View/ViewStylePropTypes.js
Libraries/StyleSheet/TransformPropTypes.js
website/layout/AutodocsLayout.js
website/server/extractDocs.js

Show the proper shape of `transform` props:
Currently it is just `transform: [object]`, so this should make it much clearer in the docs as well as properly validate.
cc @vjeux @ide

Clarify transform for ViewStyleProps, include children in union prop docs

---

docs/NativeComponentsIOS.md

Update the event mapping link: update line number from 1146 to 1165

Update link in Native UI Components (iOS) guide

---

.flowconfig
Examples/SampleApp/_flowconfig

Each version of Flow includes breaking changes, so let's be extremely specific which version of Flow each generated project is expected for 0 errors. We will bump this dependency as new versions of Flow are released and as we update react-native to work with the new version of Flow.
I tested by doing
```Bash
cd react-native
mkdir Testing
cd Testing
../init.sh Foo
cat .flowconfig
```

Specify Flow version in SampleApp .flowconfig

---

docs/NativeComponentsIOS.md

requireNativeComponent should be called after the wrapper component is fully defined, including its static properties.

Move requireNativeComponent call below the complete MapView definition

---

website/jsdocs/jsdocs.js

Summary:
The function definition and body can be in different places for multi-line declarations, so the docblock might not get pulled in. None of the existing docs seem to be affected, but putting up the fix for posterity.
Test Plan:
I modified `AlertIOS.alert` (in Libraries/Utilties/AlertIOS.js) to actually have a docblock, and ran `website/publish.sh` (with the push bit commented out). The added doc doesn't get picked up with the current code, but it does with the fix.
PS @vjeux: seems like https://github.com/facebook/react-native/commit/14c5a23eabe95a1741b601f2161476bcadecc78c never got merged in?

Fix jsdocs for multi-line ES6-style methods

---

website/server/extractDocs.js

SegmentedControlIOS is added since issue #534 #564, but the website doesn't have anything about it.

Add SegmentedControlIOS documentation to website

---

Libraries/Sample/Sample.android.js
Libraries/Sample/Sample.h
Libraries/Sample/Sample.ios.js
Libraries/Sample/Sample.m
Libraries/Sample/Sample.xcodeproj/project.pbxproj
Libraries/Sample/package.json
local-cli/cli.js
local-cli/generator-utils.js
local-cli/init.js
local-cli/new-library.js
react-native-cli/index.js

This PR adds a `react-native new-library <LibraryName>` command to the CLI. It's a little rough at the moment, but works pretty well. It does the following:
* Creates a new directory under `Libraries/LibraryName`
* Copies the sample library from react-native core at `Libraries/Sample` into this dir. This includes an `.xcodeproj` file, an `RCTLibraryName.h/m` with bridging set up, an iOS implementation and an Android stub.
* Replaces sample with the appropriate module name.
* Generates a `package.json` for the module, with a `react-native` keyword. Easing publishing to NPM.
* Prompts the user to link their new library in Xcode.
It's implemented using the same infrastructure as the `react-native init` command, now rewritten in Node as of #440.
Hopefully this will make it quicker and easier …

[CLI] New Library Generator

---

react-native-cli/index.js

`React` (with a capital) should be a reserve word and should not be used as a project name since it will break the Sample app when generated.
Previously, the CLI replaced all occurrences of `SampleApp` with whatever the user specified. If they happen to input 'React', it would generate this:
```javascript
var React = React.createClass({ ...
...
AppRegistry.registerComponent('React', () => React);
```
...which is a redefinition of React, causing `createClass` to not be defined, in turn causing the app to crash on the very first run after init, without the user modifying anything.
This commit adds a validation check prompting the user that `React` is not a valid project name.
Discussion here: http://stackoverflow.com/a/30416864/4932710

[CLI] Validation check for "React" package name

---

Libraries/Components/Touchable/TouchableOpacity.js
docs/NativeModulesIOS.md

Add doc warning stating that TouchableOpacity can only support a single child

---

README.md
website/src/react-native/index.js

The examples for Extensibility on the home page are broken :(.
RCT_EXPORT_MODULE() is missing, and RCT_EXPORT_VIEW_PROPERTY's signature has changed to accept a type as the 2nd argument.

Correct homepage code examples

---

docs/JavaScriptEnvironment.md

This PR needs review for accuracy of the links, and to add links for those which aren't linked. I couldn't find references to them in the babel documentation.
Fixes #274

[Docs] update JS environment documentation for Babel

---

docs/NativeModulesIOS.md

This may be common knowledge for most Swift/ObjC guys, but it took me quite a while to figure out why I was getting an error when creating/exporting my module. As a web guy coming to the "native" world, it was a bit confusing. I would imagine a lot of RCTN users will be in the same boat.
This is in regards to the following issue https://github.com/facebook/react-native/issues/1468

Adds additional info for creating Swift modules

---

Libraries/StyleSheet/TransformPropTypes.js

For documentation about how `transformMatrix` cannot be used simultaneously with `transform`.  Also, deprecation warning for `transformMatrix`.

[Docs] Note about transformMatrix

---

docs/DirectManipulation.md
docs/NativeComponentsIOS.md

If someone could read this over and give me some feedback it would be much appreciated.
Addresses #1390

[RFC: Docs] Add DirectManipluation guide to explain setNativeProps

---

docs/Troubleshooting.md

Creating a new section called *Xcode Build Failures* to add in issues that people might hit as per learnings gathered from the Issues that are raised.
Verify here: https://github.com/paramaggarwal/react-native/blob/troubleshooting/docs/Troubleshooting.md

Add an 'Xcode Build Failures' section

---

docs/Accessibility.md
docs/Animations.md

After working with Georgiy on adding a bunch of accessibility support to React Native, it seemed fitting to add a docs page to illustrate how developers can leverage this new support in their React Native apps.

Add docs page for accessibility support

---

website/layout/AutodocsLayout.js
website/server/extractDocs.js
website/src/react-native/css/react-native.css

On rnplay.org, we host a modified copy of UIExplorer which allows direct routing to a specific example in an in-browser simulator.
This PR introduces a single 'run this example' link in the documentation for AlertIOS, plus a tentative framework for adding more runnable links down the road.
See https://rnplay.org/apps/l3Zi2g?route=AlertIOS&file=AlertIOSExample.js
The link prepares the simulator to run the example and opens a file editor to the example code.

Start adding links to runnable examples in the documentation

---

.travis.yml
package.json
packager/react-packager/src/JSTransformer/__tests__/Cache-test.js

[This is a preview diff for getting RN's tests to pass with a future version of jest that supports io.js and other future versions of Node. This can be merged once the diff to update jest is merged upstream and published.]
Updates the tests in small ways so they run on io.js with two updates:
- The Cache test which relies on Promises uses `runAllImmediates` for modern versions of Node because bluebird uses `setImmediate` instead of `process.nextTick` for Node >0.10.
Test Plan: Run `npm test` with the latest version of jest.

[Tests] Update tests to run on io.js with the latest version of jest

---

.flowconfig
Examples/Movies/SearchScreen.js
Examples/SampleApp/_flowconfig

This should fix tests.
Test Plan: Run Travis CI tests. Also run the movies app and verify that there are no invariant violations.

[Flow] Update flowconfig's version req to 0.13.1, fix Movies example typechecking

---

docs/NativeModulesIOS.md

It looks like in the various changes to native module events, the documentation has become a little confused. As far as I can tell, if you use `sendAppEventWithName` then the `NativeAppEventEmitter` is used and if `sendDeviceEventWithName` then it should be `DeviceEventEmitter`.

Update NativeModule documentation to show correct event emitter usage

---

docs/EmbeddedApp.md
docs/GettingStarted.md
docs/Tutorial.md

It's pretty straightforward -- io.js is available through Homebrew so all you run is `brew install iojs` and then you can still run `node` from the command line. Also mentioned nvm since it's really good for switching between Node/io.js versions.
Docs for #1737

[Docs] Update installation docs to reference io.js instead of Node

---

docs/Animations.md

We should wait to merge this until the new API is available.
Let me know if you have any feedback, either on the docs themselves or the actual API :)

Add new Animated API to animation docs.

---

docs/Animations.md

I was going through the animated documentation and noticed that the example for the Input Events didn't match the variables in the paragraph above. Simple fix.
cc @sahrens

[Docs] Fix Animated example for onScroll and onPanResponderMove to match paragraph description

---

docs/NativeModulesIOS.md

Explains the use of `RCT_ENUM_CONVERTER` for using `NS_ENUM` arguments in exported functions.

Enum Constants Explanation

---

website/src/react-native/404.js

404s on the website currently redirect to code.facebook.com because we have no root 404.html - this adds one that will be generated by the website script, that redirects all 404s to the root docs page.

Adding 404.js to catch 404s on website

---

docs/Accessibility.md
docs/DirectManipulation.md
docs/EmbeddedApp.md
docs/JavaScriptEnvironment.md
docs/LinkingLibraries.md
docs/NativeComponentsIOS.md
docs/NativeModulesIOS.md
docs/RunningOnDevice.md
docs/Testing.md

This is in preparation for open sourcing React Native for Android.
Also add hyphens to URLs for consistency. This can break people's
browser bookmarks but it's better to be consistent and we can
redirect to docs: https://github.com/facebook/react-native/issues/2137
Test plan: Ran the website locally using `cd website; npm start`
and checked all pages render correctly.
http://i.imgur.com/RrPNgRr.png
Will update "Getting Started", "Tutorial", "Debugging" and
"Testing" separately.

[docs] Make it clear which Guides are platform-specific

---

docs/EmbeddedApp.md
docs/GettingStarted.md

Clarify that io.js is the modern version of Node and explain a little more about how to get set up with nvm, and that it lets you switch between multiple io.js/node versions.

[Docs] Explain more about nvm in the io.js setup docs

---

website/core/Site.js
website/layout/AutodocsLayout.js
website/layout/DocsLayout.js
website/layout/PageLayout.js
website/src/react-native/support.js

This adds `title` to `Site` so a page title can be passed in and prepended to the default title (also applies to `og:title`.)
Before
After

[Docs] Add dynamic page title

---

docs/EmbeddedApp.md
docs/GettingStarted.md

The ws module has not been updated to work with 3.x quite yet.

[Docs] Update setup instructions to install io.js 2.x instead of latest

---

website/layout/AutodocsLayout.js
website/src/react-native/css/react-native.css

We are annotating platform-specific props with a special @platform tag in the docblocks. This pull request adds a little [ios] tag before the name and sorts the props such as generic ones are before platform-specific ones.

[Website] Platform-specific props

---

react-native-cli/index.js

Currently `npm install` outputs few pages of useless stuff that
new users shouldn't care about. Instead, let's hide it by default
and print it out only when something goes wrong.
@amasad am I missing anything?

Hide npm output when doing react-native init

---

docs/EmbeddedApp.md
docs/GettingStarted.md

nvm is way better than homebrew for managing node installations:
- can install multiple versions
- can choose which version of node to install
- easy to clean up under ~/.nvm
- there are still some rough edges with /usr/local on El Cap -- nvm avoids those altogether
cc @vjeux

[docs] remove instructions to install node/io.js with brew

---

package.json

npm install will get a little nicer since it can read from npm instead of always having to redownload from github.
cc @cpojer

[jest] Update jest-cli version to 0.5

---

.travis.yml

There was a problem where NVM_DIR wasn't correctly configured, which meant that `npm install` was using whatever version of Node was on the system (0.12 in this case) despite having run `nvm use iojs-v2`. Fixing up NVM_DIR fixes the `npm install` errors and builds the native npm packages for the right version of Node.

[Travis] Put $PWD in front of nvm  (fixes npm install)

---

docs/Troubleshooting.md
local-cli/new-library.js

https://facebook.github.io/react-native/docs/linking-libraries-ios.html is the correct page, otherwise it will just redirect to the 'Getting Started' page

Changing Linked Libraries URI to point to the right page

---

Examples/SampleApp/iOS/SampleApp.xcodeproj/project.pbxproj
local-cli/init.js

Fixed #2454. Verified by patching in the GitHub `react-native` into a new project's `node_modules`, deleting all other project artifacts except for `package.json`, and then re-generating the project artifacts using
```
node -e "var cli = require('./node_modules/react-native/cli'); cli.init('.', 'BlablaApp');"
```

Fix header paths in Sample/template Xcode project to make a fresh project build again

---

website/jsdocs/jsdocs.js
website/layout/AutodocsLayout.js
website/server/extractDocs.js

The `Animated` module exposes a lot of functionality, including internal classes. This diff extracts properties and classes from modules and renders them recursively.
This also adds `Animated` to the autogen docs now that they more capable, although it needs way more docblocks and such which will come later.
Before:
After:

[Docs] Expand API parsing and rendering

---

.travis.yml
scripts/objc-test.sh

Use Xcode 6.4 instead of Travis' beta support for 6.3.

[Travis] Update CI to run with Xcode 6.4

---

react-native-cli/CONTRIBUTING.md

I was following `CONTRIBUTING.md`, specifically the section on using Sinopia for testing local changes. The setup did not cover how to handle an error that comes up when you try to publish to your private repo for the first time:
`npm ERR! need auth auth and email required for publishing`
You need to setup Sinopia to allow adding users before being able to publish locally. I updated the doc to cover this additional bit of setup.

[CLI] Updated contributing guide to deal with Sinopia publishing issue

---

docs/GettingStarted.md

The instructions as given did not work. The reason they did not work was that, while my .bashrc was made aware of nvm, my running bash process did not know about nvm until I ran ". ~/bashrc", after which things worked as expected.

Specify missing step

---

react-native-cli/index.js

Fixes #2225
Adds support for returning current version number:
`react-native -v`
OR
`react-native --version`
The version number returned is pulled from `package.json`

[CLI] Add version argument

---

website/src/react-native/showcase.js

Spritz reader for Pocket articles
github: https://github.com/liubko/FastPaper
app store: https://itunes.apple.com/us/app/fast-paper/id1001174614?mt=8

Showcase: add 'FastPaper' app

---

docs/EmbeddedApp.md
docs/GettingStarted.md
docs/Testing.md

The io.js codebase has been rebranded as "Node.js", so moving forward everyone should install the latest version of Node. The name "io.js" is no longer.

[Docs] Update RN website docs to mention Node 4+ instead of io.js

---

Examples/Movies/Movies/AppDelegate.m

Re discussion in #2705, added the missing `platform=true` for the sample movies app. Also added `dev=true` because the other sample apps included it as well.
@ide

[iOS] Add missing platform param for the movies app

---

docs/GettingStarted.md

Lots of people keep asking why they get a red screen telling them to connect to a dev server when using their device. Most have followed the "Getting Started" guide, but didn't notice the "Running on Device" section since it is kinda buried in the sidebar and isn't linked to from anywhere.

[Docs][Android] Adds "Running on Device" note

---

.travis.yml

The automated tests will install Node 4.x with nvm before running.
Test Plan: See if Travis tests pass.

[Node 4] Update .travis.yml to install Node 4.x

---

local-cli/generator-android/templates/package/MainActivity.java

It appears that the default Android activity generated by react-native `init` doesn't pass the `onBackPressed` event to the JS, so it can't be handled. I've added a block taken from the [Movies example](https://github.com/facebook/react-native/blob/42eb5464fd8a65ed84b799de5d4dc225349449be/Examples/Movies/android/app/src/main/java/com/facebook/react/movies/MoviesActivity.java#L76-L83) to the default template so the button press will be handled correctly.
I've tested with an app generated by `react-native init` and with the addition of this override `BackAndroid` works as expected.

handle back button press in JS

---

docs/Accessibility.md
docs/DirectManipulation.md
docs/EmbeddedApp.md
docs/KnownIssues.md
docs/LinkingLibraries.md
docs/NativeComponentsAndroid.md
docs/NativeComponentsIOS.md
docs/NativeModulesAndroid.md
docs/NativeModulesIOS.md
docs/RunningOnDeviceAndroid.md
docs/RunningOnDeviceIOS.md
docs/Testing.md

This screenshot explains everything:
If this would be accepted, I'll do the same with components.

[Docs] Split iOS and Android docs into different categories

---

website/server/extractDocs.js

Animated.js has been renamed (and moved) to AnimatedImplementation.js, so we need to update the path and add another translation rule.

Fix website with Animated

---

Libraries/Sample/Sample.android.js
Libraries/Sample/Sample.ios.js

1. Use singlequote instead of doublequoe on Sample.android.js
1. Remove invariant of Sample.ios.js that is not used

[Cosmetic] Fix some lint warnings

---

.travis.yml

- Uses the Xcode 7 image
- The new image includes xctool 0.2.5 (current)
- Removes the `brew update` command, which needed to fetch a lot of data
- Disables the npm spinner before installing flow-bin
- Uses `$TMPDIR` instead of spinning up Node

[Travis] Use Xcode 7 image, remove brew update, install nvm directly

---

.travis.yml

The packager and cli tests now run independently of the RN JS tests. When the packager moves to its own repo we can just remove the packager entry from .travis.yml.
The cli tests are also marked as allowed to fail for now.

[Tests] Move the packager and cli tests to separate matrix entries

---

docs/GettingStarted.md

The nvm maintainers have their own recommended installation instructions (via shell script or git checkout), which are linked to from the docs.
Fixes #3037

[Docs] Remove recommendation to install nvm from brew

---

local-cli/init.js
react-native-cli/index.js

local-cli was getting the appName from process.argv instead of using appName parameter.

Use the right appName on init

---

docs/JavaScriptEnvironment.md

This is an updated copy of #1993, which was approved by @vjeux but hasn't been rebased. It whitelists the es6 module syntax and updates the JS Environment docs to match. cc @ide @hkjorgensen

enable es6 module syntax

---

local-cli/generator/templates/_gitignore

Adds `.gitignore` entires for the Android environment. When running `react-native run-android`, the build will generate `android/build` and `android/.gradle`. This will exclude the generated files from VC.

[Android] .gitignore entries for generator template (previously SampleApp)

---

website/src/react-native/showcase.js

Added Formations Factory Company name search app to the list of showcase apps.
iTunes url: https://itunes.apple.com/us/app/company-name-search/id1043824076
Thank you for React Native! It was a pleasure to work with. It took us only a few days to create this app! :)

Add Formations Factory Company name search app to [Showcase]

---

react-native-cli/index.js

Add `--verbose` option to React-Native-CLI in order to debug slow running project initialization. Normal project initialization still hides npm outputs as before.

Add --verbose option to react-native-cli (fixes #2797)

---

local-cli/init.js

https://github.com/facebook/react-native/commit/046d8d2dee91e11965adf084a2a41a7b9ac6213a did not do the job because `process.args` is not a thing.
Ran into this issue and manually verified that this worked.
@ide @foghina for review and quick merge please

[cli] make init backwards-compatible for real

---

docs/Performance.md

In the Performance view of the documentation, the link "(Read about why you should probably use Navigator anyways.)" is broken. Clicking here ends up to a redirection to https://code.facebook.com/ instead of https://facebook.github.io/react-native/docs/navigator-comparison.html. This fixes it by giving a correct relative path.

fix navigator comparison link in performance doc

---

website/src/react-native/css/react-native.css

Copy method names by double clicking added platform name to clipboard. 
Annoyed me couple of times. Now double clicking on method name in documentation will only select the name of the method.

Make platform name unselectable

---

website/src/react-native/showcase.js

We are using React Native on our app's homepage for the Daily Fashion Feed - a curated list of content to discover inspiring content. We recently went live to 100% and happy to share this news with the community.
Also, we are shipping JS updates on the fly to our customers and loving it!
(Myntra is India's largest online fashion retailer, a subsidiary of Flipkart Pvt. Ltd. out of Bangalore, India. We recently went app-only by shutting down our website.)

Add Myntra to showcase

---

.gitattributes

Added a .gitattributes file, ensuring that Bash script source files (gradlew and
*.sh) have normal Unix LF line endings even on Windows.  This change is needed
so gradlew, packager.sh, and other Bash scripts can run on Windows (under Cygwin).
On Windows the rest of the source files will typically have CR+LF endings (Git
default), but Bash scripts need to have LF endings to work, thus this override
to force that.

Force LF line endings for Bash scripts, so they work on Windows

---

website/publish.sh

In #3421 we created a new folder but it didn't get picked up by the publish script.
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
js/
```
The reason is that `git diff-index --quiet HEAD --` returns 0 for untracked files. But, if we add before, it returns 1.
It still returns 0 if we add but there's nothing changed

[website] Support pushing new files

---

website/src/react-native/showcase.js

This is my open source app called Kakapo (https://itunes.apple.com/gb/app/kakapo/id1046673139?ls=1&mt=8).
Kakapo is an ambient sound mixer for relaxation or productivity that is currently available on the App Store.
The code on GitHub is available at https://github.com/bluedaniel/Kakapo-native
Thanks so much for your incredible work on React!

Adding Kakapo to the app showcase

---

website/src/react-native/showcase.js

Hi colleagues!
I am very grateful to Facebook React Native team. Your product help me release iOS app as soon as possible and reuse 70% of web and Mac OS X version code base, including Reflux storages and actions.
https://itunes.apple.com/us/app/raindrop.io-keep-your-favorites/id1021913807

Add Raindrop.io to showcase

---

website/src/react-native/showcase.js

LoadDocs is a a React Native iOS app to help trucking drivers scan their documentation (Bill of Ladings, Proof of Deliveries, etc) from the road. 
We are currently working on re-writing our existing Android app to use React Native as well. 
App store link: https://itunes.apple.com/us/app/loaddocs/id1041596066

Add LoadDocs to showcase

---

CONTRIBUTING.md

Since it's official now https://facebook.github.io/react/blog/2015/10/19/reactiflux-is-moving-to-discord.html

Add info about react-native channel on DiscordApp

---

scripts/e2e-test.sh

Internally we don't mirror `scripts` folder from GitHub, which means
when importing #3523 changes to `scripts/e2e-test.sh` will not make it to
GitHub. This commit contains those changes.
I'll merge this once #3523 (D2557923) lands

Fix e2e tests

---

docs/Performance.md
docs/SignedAPKAndroid.md
docs/Upgrading.md

cc @mkonicek @frantic
I added a note on the upgrading page about the `upgrade` command not being available yet. We should remove this after next week's release.

[docs] add bundle and upgrade docs

---

react-native-cli/package.json

React Native's packager now relies on modern V8 so it depends on modern Node. The CLI tools actually run with older versions of Node but the version constraint in the CLI's package.json accomplishes two things:
- Lets us rely on modern V8 in the CLI so we don't have to think about which JS features we can use
- Fails faster up front. So if someone has Node 0.10 for example they will get an error when setting up the CLI tools instead of later on in the process.

[CLI] Add Node >= 4 requirement to CLI tools

---

react-native-cli/index.js
react-native-cli/package.json

We get a bunch of bugs because people are running old versions of Node that don't support modern JS. We have "engines" entries in the package.json files to catch this earlier but printing an explicit error message will also make this clear.
Test Plan: Changed react-native's package.json to require Node >= 5 and got an error message when running the CLI with Node 4.

[CLI] Make `react-native init` check your Node version

---

docs/NativeModulesAndroid.md

Noticed this discrepancy in the docs, `RCTDeviceEventEmitter` is not exported, `DeviceEventEmitter` is.

Fix android native modules to reference right export

---

website/server/extractDocs.js

@nicklockwood  @mkonicek website build was broken after the asyncstorage refactor which landed on master today.

fix website build after asyncstorage changes.

---

docs/KnownIssues.md

After https://github.com/facebook/react-native/commit/77272d5a9193762b8668c99d54f5bb9a3e423a9e / D2574937, transparent views (managed by RN) on iOS now receive touch events. The code sample from the Known Issues section is now a UIExplorer example, and you can't tap the TouchableOpacity button because the transparent overlay is intercepting touches (which matches the behavior on other platforms).

[Docs] Remove section on how transparent views don't receive touches on iOS

---

docs/Network.md

- Mention that Fetch returns a Promise 
(makes example with .then clearer to newcomers to ES6/ES7)
- Add example of Fetch usage with second argument
(helps clarify how e.g., a POST request to an API might be constructed)

extend Network/Fetch API documentation

---

website/src/react-native/css/react-native.css

Summary: The showcase page is where you go to see examples of RN projects deployed in the wild. Chances are you're going to want to hit that page on your mobile device to view and install them from the App Store / Google Play. Four columns looks great on a large screen. But four columns is difficult to read/browse on small screens. So I created a single-column layout for small screens and a two-column layout for tablet screens. Still four columns on large screens. Cheers!

Added media queries for Showcase page in docs

---

docs/Images.md
docs/Upgrading.md

We changed the Xcode integration a bit. Instead of running `react-native bundle` manually there is now a script that runs as Xcode build phase. Upgrading can be tricky, I've added some docs on how to do this manually.

Add manual instructions on upgrading 0.13 -> 0.14

---

docs/Troubleshooting.md

Explain how to troubleshoot  'No transports available' error that appears when you require firebase before react-native.

Added section on modules that require WebSocket

---

docs/Testing.md

Since the `scriptPreprocessor.js` is removed since 14.0,
we use `preprocessor.js` instead, 
but the doc doesn't update yet.
So I do it :)

Correct the file name to preprocessor

---

docs/NativeComponentsAndroid.md

Currently there is a bug in the [Javascript Module](https://facebook.github.io/react-native/docs/native-components-android.html#5-implement-the-javascript-module) section of the "Android > Native UI Components" docs. `PropTypes` are used in the native component interface without ever being imported.
This PR updates the example in the docs to work correctly.

Import PropTypes in Native UI Android Docs

---

Examples/Movies/README.md
Examples/UIExplorer/README.md

Thought this would be helpful since people can come to the Movies example page (https://github.com/facebook/react-native/tree/master/Examples/Movies) straight from the React Native tutorial (https://facebook.github.io/react-native/docs/tutorial.html) without having read the main Examples README first.
I have completed the CLA.

Add git clone step to READMEs

---

docs/GettingStarted.md

Xcode 6 doesn't understand the annotations c5b990f65f0791041378a61cd503ccf686b00bb1 added to 0.15.0-rc. So requires Xcode 7 to build successfully.

Requires Xcode 7 or higher to run 0.15.0-rc

---

Libraries/Geolocation/Geolocation.js

Since the `Geolocation` docs explicitly contain Android instructions for a library that is not open-sourced, there should probably a sign post to Known Issues as found in, for example, the [CameraRoll documentation](http://facebook.github.io/react-native/docs/cameraroll.html#methods).
Added to the inline Geolocation.js docs:
> Geolocation support for Android is planned but not yet open sourced. See [Known issues](http://facebook.github.io/react-native/docs/known-issues.html#missing-modules-and-native-views).

[Docs] Note that Android geolocation not yet open sourced

---

docs/RunningOnDeviceIOS.md

Given some [confusion that I had around `react-native bundle`'s `--dev` flag][1], this hopes to clear some things up in the docs by…
- Removing mentions of the `__DEV__` environment variable
- I think it confuses the user on how to work with the command-line flag, and frankly it seems like an internal implementation detail from the perspective of react-native-cli. We should focus on what the `--dev` flag does (e.g., toggles dev warnings, performance optimizations).
- Adding a minimal note about native-land's build configurations and how that should be checked for production builds
[1]: https://github.com/facebook/react-native/issues/4181

[Docs] Clarify --dev flag for react-native-bundle

---

Libraries/Components/ScrollView/ScrollView.js

Updating `removeClippedSubviews` prop in ScrollView docs. Same thing as #4313.

Update removeClippedSubviews prop default value

---

docs/KnownIssues.md

From known issues: "[The overflow style property defaults to hidden and cannot be changed on Android](https://facebook.github.io/react-native/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android)"
This is not the full story. I was surprised to discover that although overflow: hidden is always true on Android, it never obeys borderRadius clipping. See: #3198. I think this is worth an extra sentence since there are design/implementation choices that can significantly simplify compensating for this, but only if known ahead of time.

[Docs] Additional note for Android borderRadius clipping #3198

---

docs/NativeModulesIOS.md

fix sample code error by removing the extra ',' and ')'

fix sample code error by removing the extra chars

---

.travis.yml
bots/code-analysis-bot.js
package.json

This runs eslint and flow and pipes the output to a node script that comments on the pull requests the same way phabricator does. It should reduce the number of lint/flow issues with pull requests without our intervention.

Code Analysis Bot

---

docs/NativeComponentsAndroid.md

The link from [native components](http://facebook.github.io/react-native/docs/native-components-android.html#5-register-the-viewmanager) to [native modules](https://facebook.github.io/react-native/docs/native-modules-android.html#content) is broken in the gh-pages docs. This PR points it to the right address in pages (note that this will break the link in the GitHub markdown view, but I think the number of people that will view the page through the docs site dwarf those who view it in the repository).

change native-modules link to work on gh-pages

---

react-native-cli/index.js

`react-native init` exhibits a typo in informing the user that the directory already exists. This PR fixes that.

Fix message when react-native init encounters existing directory.

---

docs/NativeModulesAndroid.md

Native developers may get confused by require statement.

Give more details about js require.

---

docs/LinkingLibraries.md

According to this conversation: https://twitter.com/martinkonicek/status/676698315451408384

Add a section about linking process automation using rnpm

---

Libraries/Animated/src/AnimatedImplementation.js

'AnimatedEvent' is found no where in the entire project except in the sample code for 'Animated.event'

[Doc][Minor] updated deprecated sample code in animation doc

---

docs/LinkingLibraries.md

I am not sure if this warrants a change but I had a hard time Linking my first library in my React Native project. Following the steps was pretty easy but at first glance it seems like `library-with-native-dependencies` is a real npm library.
Adding the `<>` removes any confusion and helps the reader know `<library-with-native-dependencies>` is a placeholder.

adds sample library distinction

---

docs/KnownIssues.md

as https://github.com/facebook/react-native/commit/3a3af8a385583c7aabfad5f8ff5daa69aa29953f

[Doc][minor]remove outdated info

---

react-native-cli/index.js

fixes #3771 for npm 3 and upwards

npm progress shown on react init

---

docs/Network.md

Using the provided WebSocket example under react-native 0.17, the sample code throws the following error:
"TypeError: ws.on is not a function(…)"
It's listening on ".on" which does not exist, rather than assigning a function to onopen, onmessage, onerror and onclose.
See: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

Update incorrect WebSocket example in Network.md

---

website/src/react-native/support.js

add community translation links to help spreading react-native!

add community translation links

---

packager/blacklist.js
website/core/H2.js
website/core/Marked.js
website/package.json
website/server/convert.js

I had a few issues running the website locally on Windows with npm3.
The packager was not properly ignoring the website node_modules which caused errors with the haste modules.
splitHeader didn't work properly because of \r\n
Not 100% sure about this one but the website used react@0.12 while react-page-middleware used react-tools @0.13. Updating react to 0.13 fixed the problem. I also fixed some warning about not using factory functions by using jsx instead and remove the transferPropsTo call that doesn't exist anymore in react@0.13.

Fix issues running the website locally on windows with npm3

---

website/publish.sh

Ideally we would generate/prepare circle.yml specifically for gh-pages branch but for now this one is good enough.
Having this file in circle.yml will order circleCI to ignore the branch

small hack to have circle.yml in gh-pages generated branch

---

docs/Debugging.md
docs/DevelopmentSetupAndroid.md

It's a tool for OS X that easily lets you reload developer tools menu with menubar/tray and hotkey.
It'd be great if someone forked my project and added iOS support (not sure if this is possible).

Added reference to Frappé (for OS X Android)

---

docs/RunningOnDeviceAndroid.md

As an alternative to shaking the device, you can input the key code `82` to open the dev menu.

[Docs] Adds an alternative method of opening dev menu on Android devices

---

react-native-cli/index.js

A better solution for #5169 
launch npm with spawn('cmd') on windows. @mkonicek

Fix 'Error: spawn npm ENOENT' on Windows

---

website/server/extractDocs.js

Needed to split the PR for #5209 because of the way the code is stored internally at Facebook.

Add doc for RefreshControl on the website part 2

---

docs/DevelopmentSetupAndroid.md

@satya164 The new PR for this.

Added Hyper-V Android Emulator Setup Instructions. Closes #3234

---

docs/EmbeddedAppIOS.md

Building off of the work in this PR https://github.com/facebook/react-native/pull/5284, this…
- Adds a note int he docs about adding a `localhost` exception to an embedded app's `Info.plist`
- ~~Remove the total disabling of ATS from the react-native generated iOS project in favor of a `localhost` exception~~ see https://github.com/facebook/react-native/pull/5355 per this request: https://github.com/facebook/react-native/pull/5290#issuecomment-172213709

Expand docs on App Transport Security

---

README.md

react.rocks has moved to js.coach and the packages at react.rocks aren't up to date anymore.

Correct link to former react.rocks website

---

Libraries/Components/TextInput/TextInput.js

DocumentSelectionState returns anchor and focus offsets only in focused state. So TextInput should set proper state to selectionState when blur and focus.

TextInput should call blur and focus methods of selectionState

---

Libraries/CustomComponents/NavigationExperimental/NavigationCard.js
Libraries/CustomComponents/NavigationExperimental/NavigationHeader.js
Libraries/NavigationExperimental/NavigationPropTypes.js

cherry-pick 0e997c6eabae79c99823459b39b885547f824955 into 0.26-stable:
fixes a bug where NavigationPropTypes.SceneRenderer was a plain object
re https://github.com/facebook/react-native/issues/7385

cherry-pick NavigationPropTypes.SceneRenderer bugfix

---

docs/JavaScriptEnvironment.md
docs/Navigation.md
docs/Navigators.md
docs/Networking.md
docs/UsingNavigators.md

See: b33424e5ed09f15cbfa0198a01ad372c1989f6af.
We also need 7d3fbbdb68e5015311bce60236e0ae06d62f17a2 since it is a prerequisite to b33424e5ed09f15cbfa0198a01ad372c1989f6af.
Test Plan:
http://localhost:8079/react-native/docs/using-navigators.html
Links work.

Cherry-pick: Fix Navigation Links

---

docs/Networking.md
docs/UsingNavigators.md

Similar to the `0.29-stable` cherry-pick request at https://github.com/facebook/react-native/pull/8703

Cherry-pick: 0.30-stable: Fix links from networking to navigation in The Basics.

---

docs/JavaScriptEnvironment.md
docs/Navigation.md
docs/Navigators.md
docs/Networking.md
docs/UsingNavigators.md

I saw no reason why we shouldn't add @hramos Navigators tutorial in the current `0.29` documentation.

Cherry-pick: Navigator Tutorial

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
website/core/Footer.js
website/core/HeaderWithGithub.js
website/layout/AutodocsLayout.js
website/layout/DocsLayout.js
website/src/react-native/css/react-native.css

#9149 resolved an issue where Edit on GitHub links lead to a release branch, which results in pull requests being opened against a release branch instead of master. Many issues "resolved" in this manner have already been addressed in master.
This PR is intentionally against `0.31-stable` as it is cherry-picking changes already landed to master.
See prior discussion in #9222. This new PR uses the single squashed commit, and does so against 0.31-stable, which is now the latest release.

Cherry-pick #9149 into 0.31-stable branch

---

docs/UsingNavigators.md

**motivation**
`getDefaultProps` is not available in ES6 class declaration for components. Adding it here may cause confusion to new comers.

Remove getDefaultProps from plain Javascript class

---

React.podspec

Closes https://github.com/facebook/react-native/issues/11502. We have the same problem in our app. Could you release this patch in 0.39.3, because the react-native@0.40.0 has huge breaking changes and we won't quickly update to it?

[Podspec] Fix duplicate symbols error

---

local-cli/commands.js
local-cli/eject/eject.js
local-cli/generator/copyProjectTemplateAndReplace.js
local-cli/templates/HelloWorld/android/app/src/main/res/values/strings.xml
local-cli/templates/HelloWorld/app.json
local-cli/templates/HelloWorld/ios/HelloWorld/Info.plist

This is a cherry pick of @ericvicenti's commit for the `react-native eject` command to the 0.42-stable release branch. This commit currently exists on 0.41-stable and 0.43-stable, as well as master.
Needed to unblock a release of Create React Native App to support RN 0.42.
cc @ide

Eject CLI command to re-create native folders

---

package.json
packager/package.json
packager/src/node-haste/DependencyGraph.js
packager/src/node-haste/__tests__/DependencyGraph-test.js
packager/src/node-haste/__tests__/__snapshots__/DependencyGraph-test.js.snap

Summary: This allows us to get the new fix for recovery on duplicate modules.
Reviewed By: cpojer
Differential Revision: D5128975
fbshipit-source-id: 5a2b60430bbca1806a97798c482af8522366e071
Thanks for submitting a PR! Please read these instructions carefully:
What existing problem does the pull request solve?
Version 19.0.0 of jest-haste-map is incompatible with react-native-windows.
A good test plan has the exact commands you ran and their output, provides screenshots or videos if the pull request changes UI or updates the website. See [What is a Test Plan?][1] to learn more.  
If you have added code that should be tested, add tests.
Tests were already added, this commit is just a cherry-pick.
Sign the [CLA][2], if you haven't already.
Small pull requests are much easier to review and …

packager: upgrade jest-haste-map version

---

package.json

Running npm install and then import-existing-docs.js results in error that 'front-matter' dependency is missing. Looks like the file requires it on line 13 but it's not included in package.json.
Installed and saved the file to dependency list.
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)
import docs file ran successfully and generated markdown for sidebar.

Added front-matter as dependency

---

local-cli/.npmignore
local-cli/generator/copyProjectTemplateAndReplace.js
local-cli/init/init.js
local-cli/templates/HelloWorld/_babel.config.js
local-cli/templates/HelloWorld/_babelrc

This fixes template application sample tests.
1. Fix adding __tests__ folder to npm package
2. Fix tests itself (add babel-core to deps and rename .babelrc to babel.config.js)
Unfortunately some changes can't be applied to master branch because of cli extraction. Moreover some changes (probably addition of babel-core to deps) will not be needed when jest 24 will be released. So this is path specially for 0.58-stable branch.
I think after apply this, we also should do some things:
1. Recheck npmignore patterns in master branch, remove unused and ensure that templates packed correctly.
2. Recheck our deps and config in HelloWorld template after jest 24 will be released.
Changelog:
----------
[General] [Fixed] - Fix tests in template HelloWorld application
Test Plan:
----------
```sh
cd …
```

Fix tests in template project (0.58-stable)

---

scripts/packager.sh

This PR fixes packager during **react-native run-ios** and **react-native run-android**.
On reddit and discord many developers say that **react-native run-ios** failing on 0.58. But I found that **react-native start** works just fine. So did some investigation and found that if check is false when **react-native run-ios** but true when **react-native start**.
https://github.com/facebook/react-native/blob/57ad19758db60992a4d8ab55219d86eb892ac2b0/local-cli/cli.js#L23
It checks if script is run from shell, then starts the packager. Also found that **react-native start** calls this **react-natvie/local-cli/cli.js** directly and check is true. And dug little further to find that **packager.sh** is calling **react-native/cli.js** which imports **react-native/local-cli/cli.js**, therefore check …

fix packager start in 0.58

---

local-cli/runIOS/findMatchingSimulator.js

When parsing simulator names in order to run on iOS simulator, the name now contains the prefix "com.apple.CoreSimulator.SimRuntime." Therefore the check to filter out simulators that are not iOS or tvOS needs not to check for startsWith, but rather to check for includes.
Without the fix, I am not able to start and run the iOS simulator through the react-native cli
This started happening for me after I installed the latest XCode (beta). I am currently using XCode "Version 10.2 beta (10P82s)", but I have tried using xcode-select to point towards the latest stable XCode version as well, but the problem still occurs. My version of xcrun is "xcrun version 43.1."
[iOS] [Changed]- Enabling start of iOS/tvOS simulators when simulator versions are reported with apple-prefixes.
Run the command …

Parse simulator list

---

react.gradle

Hermes command targets a wrong binary path

Fix Hermes binary path

---

react.gradle

As @HazAT pointed out (thanks!) in https://github.com/facebook/react-native/issues/25693#issuecomment-512713367, we are currently unintentionally including the source map in the release APK. This PR changes the source map output path, e.g.
```diff
-build/generated/assets/react/release/index.android.bundle.map
+build/generated/sourcemaps/react/release/index.android.bundle.map
```
[Android] [Fixed] - Remove source map from release APK
1. `react-native init test`
2. `cd test/android`
3. `./gradlew assembleRelease`
4. Check that a source map exists in `app/build/generated/sourcemaps/react/release/index.android.bundle.map`.
5. `unzip -l ./app/build/outputs/apk/release/app-release.apk | grep '\.map'` - output is empty.
6. Set `enableHermes` to `true` in `app/build.gradle`, `./gradlew clean` and …

[Android] Remove source map from release APK

---

ReactAndroid/src/main/java/com/facebook/hermes/unicode/AndroidUnicodeUtils.java

This adds the `@DoNotStrip` annotation to disallow Proguard/R8 from stripping the `AndroidUnicodeUtils` class during release build and causing a `ClassNotFound` crash.
[Internal] [Fixed] - Fixed `ClassNotFound` exception in Android during Release builds

Fix `ClassNotFound` exception in Android during Release builds

---

ReactAndroid/src/main/java/com/facebook/react/uimanager/BaseViewManager.java

Commit 1aeac1c625 erroneously added a comma and space to the end of accessibilityLabels for components which did not have additional state and hint information. This commit corrects this behavior.
[Android] [Fix] - Remove extra comma and space from accessibilityLabels on Android.
Using TalkBack's display of spoken labels, ensured that no extra symbols are added to accessibilityLabels.

Fix addition of comma at the end of accessibility labels on Android.

---

template/package.json

When using `npx react-native init Bla`, the react version that is installed there is 16.8.1 instead of the recommended 16.9.0.
This PR is to fix that.
[General] [Fixed] - Updated React version to 16.9.0
Run `npx react-native init Bla` using this PR somehow, and see if the correct react version is pulled in.

Bump react to 16.9.0

---

React/Modules/RCTTiming.m

This reverts commit 338298417f8077dee177057c57b38671b4ec8c75
This is related #26696 - an issue where the app would be closed immediately after going to background on iOS 13.1/13.2 and was investigated by @minhtc https://github.com/facebook/react-native/issues/26696#issuecomment-548056694. The commit that is being reverted is apparently causing the app to be closed immediately. This has to be reverted in master separately as the file differs there.
[iOS] [Fixed] - Reverts commit causing a crash in the background
Create an empty app on 0.61.x with a timer, put it in the background.

Reverts "Timing: Fixes timer when app get into background (#24649)"

---

Libraries/Modal/RCTModalHostViewNativeComponent.js
Libraries/YellowBox/UI/YellowBoxInspectorHeader.js

Fixes Flow errors that surfaced with 0.62.1 release. 
Targeting `0.62-stable` branch, because this is an effect of applying patches that were relying on prior changes:
- YellowBox is now removed from from master 
- `BubblingEventHandler` was removed in 0676ebf79a3fd98ed411a3a37c1ee121eb3eef68 which partially built on top of bd2b7d6c0366b5f19de56b71cb706a0af4b0be43, later reverted in 27a3248a3b 
cc @alloy @kelset 
[General] [Fixed] Flow errors from YellowBox and BubblingEventHandler
Flow check passes

[General] [Fixed] Flow errors from YellowBox and BubblingEventHandler

---

package.json

This PR is duplicate of https://github.com/facebook/react-native/pull/30451 for 0.64 branch, and will fix android packaging.
[Internal] [Changed] - include android in npm package
With this change test-manual-e2e.sh will run successfully, previous it was failing due to duplicate classes error.

include android in npm package

---

scripts/react_native_pods.rb

https://github.com/facebook/hermes/releases/tag/v0.7.2 is out so we can bump the pod version 🎉
Question:
Is `~> 0.7.2` too strict? Would `>= 0.7.2` be better?
Also, It doesn't look like we are restricting any version on the trunk?
[INTERNAL] - Bump Hermes version
Quoting from <https://github.com/facebook/hermes/issues/373>
> I can verify 0.7.2 is working with `USE_HERMES=1 bundle exec pod install --repo-update` 🎉
> Here is a screenshot of the rn-tester connected with the Hermes debugger within Flipper. The code is borrowed from https://github.com/facebook/hermes/issues/403 to prove that the `?.` fix asked by @janicduplessis is patched ;)

Bump Hermes to 0.7.2 for v0.64

---

Libraries/ReactNative/AppContainer.js

Reverting the legacy rootTag childContext in AppContainer for 0.65 release. It will be deprecated and removed in the following release.
[General] [Changed] - [AppContainer] Add back legacy rootTag childContex 
CI test run

[AppContainer] Add back legacy rootTag childContex

---

README.md

Fixes: #32618
This small PR updates the `0.64-stable` branch Readme file which listed the incorrect (old) minimal requirements for Android and iOS devices. The updated sentence has been taken from the next release branch.
N/A
N/A

[0.64][readme] fix supported os versions

---

React/Modules/RCTI18nUtil.h
React/Modules/RCTI18nUtil.m

This reverts commit fcead14b0effe2176a5d08ad50ee71e48528ddbd.
This should close https://github.com/facebook/react-native/issues/32509 . There was a bug where il8nManager.forceRTL() wouldn't work on app launch, and required an app restart. That was caused by an earlier change (https://github.com/facebook/react-native/pull/31032) which should not be necessary (the deadlock it was attempting to fix was actually caused by separate code).
[iOS] [Fixed] - Fixed bug where forceRTL did not work on app launch
Pull Request resolved: https://github.com/facebook/react-native/pull/32574
Test Plan: Simple revert back to previously working code.
Reviewed By: RSNara
Differential Revision: D32315034
Pulled By: GijsWeterings
fbshipit-source-id: dae6c1f0a2481e53f2f1e80f1ac083947681ef99
[CATEGORY] [TYPE] - …

Revert "Fix Deadlock in RCTi18nUtil (iOS) (#31032)" (#32574)

---

scripts/react_native_pods.rb

ℹ️ **This is a cherry-pick of #32633 to `0.66-stable`**
The `__apply_Xcode_12_5_M1_post_install_workaround` script changes the `IPHONEOS_DEPLOYMENT_TARGET` to `11.0` for all pods. This causes problems if the pods were targetting `12.0` or higher. Many expo modules are targetting `12.0`.
I fixed this issue by checking the existing version and only bumping the target if it is lower than `11.0`. 
See also: this discussion post by @mikehardy https://github.com/reactwg/react-native-releases/discussions/1#discussioncomment-1619523
[iOS] [Fixed] - __apply_Xcode_12_5_M1_post_install_workaround causing pods targetting iOS 12 and above to fail
1. pick an iOS Pod that has a minimum deployment target of iOS 12 or higher, I chose the Braintree package
2. `npx react-native init myrnapp`
3. Open …

Cherry pick "Fix post_install_workaround downgrading development targets" to 0.66-stable

---

ReactAndroid/build.gradle
template/android/app/build.gradle

On Windows there are limits on number of character in file paths and in command lines
Ref: https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Path-Length-Limits
NDK allows circumventing command line limits using response(RSP) files as inputs using NDK_APP_SHORT_COMMANDS flag.
Windows can support long file paths if configured through registry or by prefixing all file paths with a special character sequence
The latter requires changes in NDK. And there are tools in NDK (AR) which is not able to handle long paths (>256) even after setting the registry key.
The new architecutre source tree is too deep, and the object file naming conventions in NDK makes the matters worse, by producing incredibly long file paths.
Other solutions such as symlinking source code …

Building new architecture sources on Windows

---

scripts/react_native_pods.rb

`pod install --project-directory=ios` fails when Hermes is enabled:
```
% pod install --project-directory=ios
[Codegen] Generating ios/build/generated/ios/React-Codegen.podspec.json
[Hermes] Extracting Hermes tarball (5244f8)
[DEBUG] pwd: /~/example
[DEBUG] cp: cp ../node_modules/react-native/sdks/hermes-engine.podspec ../node_modules/react-native/sdks/hermes/hermes-engine.podspec
warn Multiple Podfiles were found: ios/Podfile,macos/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
Auto-linking React Native module for target `ReactTestApp`: ReactTestApp-DevSupport
Analyzing dependencies …
```

Fix `pod install --project-directory=ios` failing when Hermes is enabled

---

scripts/hermes/hermes-utils.js
sdks/hermes-engine/hermes-engine.podspec

On RN 0.69, we added a check for current branch/remote/tag.
As they execute eagerly, users which are not inside a git repo will experience a failure. This is addressing it.
[Internal] - Lazily query for git branch & remote
I've tested those changes on a newly created project with RC4 and verified that they work correctly.

Lazily query for git branch & remote

---

.circleci/config.yml
scripts/react_native_pods.rb

With RC5, we're not effectively downloading the Hermes tarball from the Github releases. Here the fix.
[Internal] - Fix Hermes not being downloaded on RC5 on iOS
This PR should be merged on the release branch alongside this cherry-pick:
https://github.com/facebook/react-native/commit/f1775ba67b1aa4428dc769b9b2bdd2680dbd30de
How I tested this.
1. `npx react-native init RN069 --version next --skip-install`
2. Replicate the aformentioned cherry-pick with: `echo "hermes-2022-05-20-RNv0.69.0-ee8941b8874132b8f83e4486b63ed5c19fc3f111" > node_modules/react-native/sdks/.hermesversion`
3. Apply this PR to the `react_native_pods.rb` file.
4. Enable Hermes inside the Podfile
5. Edit the following file to point to a tarball on my fork (which doesn't contain the extra .podspec inside it): …

Fix Hermes not being downloaded on RC5

---

package.json
packages/rn-tester/Podfile
scripts/cocoapods/FlipperConfiguration.rb
scripts/react_native_pods.rb
template/ios/Podfile

This PR backports FlipperConfiguration and the changes to the template Podfile so that apps created with React Native does not install Flipper pods when the dependencies are installed with `PRODUCTION=1 bundle exec pod install`.
When dependencies are installed using that command, Flipper won't be added as a dependency to the project and we can build the app using the Release schema. 
[iOS] [Fix] - Make sure that Flipper pods are not installed when creating a release build.
CircleCI passes

[fix] backport FlipperConfiguration from main

---

package.json
yarn.lock

Upgrades the React Native CLI to v8.0.3 which should fix issues reported in https://github.com/reactwg/react-native-releases/discussions/23#discussioncomment-3006097. I'm still waiting for some 3rd person to verify it works and doesn't break other functionality uncaught by our own tests.
Pointing directly to `0.69-stable` branch.
[General] [Changed] - Upgrade RN CLI to v8.0.3
CI

Upgrade RN CLI to v8.0.3

---

.circleci/config.yml
scripts/hermes/hermes-utils.js
scripts/hermes/prepare-hermes-for-build.js

This PR ensures that we can build Hermes from source also when we are creating prs against stable branches.
It also revert the changes of #34223 because they did not fix the issue.
[General] [Changed] - Make sure we can build Hermes from source when PR are opened agains `-stable`
Tested locally + CircleCI is green (a part from `test_ios_unit`)

[FIX] Build hermes from source on PR against stable

---

scripts/react_native_pods.rb

Some third party modules will have build errors on react-native 0.69.1 if they have dependency to `React-bridging` (or `ReactCommon/turbomodule/core` from transitive dependency). We setup correct header search paths in [ReactCommon.podspec](https://github.com/facebook/react-native/blob/f3db6cc52792e3006a16408df4ae40f3aee19a86/ReactCommon/ReactCommon.podspec#L35). We should also apply the change to third party modules. This PR is a workaround for the migration without introducing breaking changes to third party modules.
Note that is pr is based on 0.69-stable. Because on main branch, the react_native_pods.rb has much refactoring. I'll probably create a new pr based on main branch after this one landed.
Fix #34102 
[iOS] [Fixed] - Fix React-bridging headers import not found
```
$ npx …
```

Fix React-bridging header not found for third party modules

---

package.json
yarn.lock

Upgrades the React Native CLI to v8.0.4 which should fix issues with resolving package.json in packages with "exports", reported in https://github.com/react-native-community/cli/issues/1168. 
Pointing directly to `0.69-stable` branch.
cc @fortmarek @kelset 
[General] [Changed] - Upgrade RN CLI to v8.0.4
CI

Upgrade RN CLI to v8.0.4

---

package.json
packages/react-native-gradle-plugin/package.json
yarn.lock

Upgrades react-native-gradle-plugin to 0.70.1 to include fixes picked for 0.70 RC2.
cc @kelset @cortinico @Titozzz 
[General] [Changed] - Upgrade react-native-gradle-plugin to 0.70.1.
CI

Upgrade react-native-gradle-plugin to 0.70.1

---

ReactAndroid/src/main/java/com/facebook/react/fabric/jni/Android.mk
ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni/Android.mk
ReactAndroid/src/main/jni/react/jni/Android.mk
ReactCommon/react/renderer/components/progressbar/Android.mk
ReactCommon/react/renderer/components/slider/Android.mk
ReactCommon/react/renderer/components/switch/Android.mk
ReactCommon/react/renderer/textlayoutmanager/Android.mk

We will not build the shared library named reactnativeutilsjni as it is built from the same sources as reactnativejni. It makes sense to remove the duplicate copy. This change should help reduce the `apk` size for android apps.
This is similar to a recently merged PR in main:
https://github.com/facebook/react-native/pull/34339
[Android][Changed] - Replaced reactnativeutilsjni with reactnativejni in the build process to reduce size
Built react-native 0.68 from source and it builds the `.aar` successfully.
It has to be tested against:
1. New Architecture
2. Old Architecture

Let's not build reactnativeutilsjni shared library

---

package.json
packages/react-native-gradle-plugin/package.json
yarn.lock

Upgrades react-native-gradle-plugin to 0.70.1 to include fixes picked for 0.70 RC2.
cc @kelset @cortinico @Titozzz
[General] [Changed] - Upgrade react-native-gradle-plugin to 0.70.1
CI

Upgrade react-native-gradle-plugin to 0.70.2

---

React/CoreModules/CoreModulesPlugins.h
React/CoreModules/CoreModulesPlugins.mm

Summary:
This diff reverts D40716048 (https://github.com/facebook/react-native/commit/279cfec55fdf404fdb9198edbb37d3adfdfb3bf1) (https://github.com/facebook/react-native/pull/35047) which breaks RCTImageLoader.
https://pxl.cl/2jKrM
Those files are auto-generated and are not supposed to be edited manually.
Changelog: [iOS] [Fixed] - https://github.com/facebook/react-native/pull/35047 reverted.
Reviewed By: cipolleschi
Differential Revision: D40979350

Revert: make RCTBlobManager TurboModule-compatible

---

scripts/bump-oss-version.js
scripts/prepare-package-for-release.js
scripts/release-utils.js

When dry-run in stable branch, the tag already exists. We are bypassing the tag-existence check when in a dry-run to have the CI pass
[General] [Fixed] - Bypass tag version check when dry-run
CircleCI

[LOCAL] Bypass tag check in dry run

---

.circleci/config.yml
packages/rn-tester/Podfile
scripts/cocoapods/__tests__/jsengine-test.rb
scripts/cocoapods/jsengine.rb
scripts/hermes/prepare-hermes-for-build.js
scripts/test-e2e-local.js
sdks/hermes-engine/hermes-engine.podspec

Use `REACT_NATIVE_CI` instead of `CI` environment variable to trigger building Hermes from source on CircleCI. `CI` envvar is defined in many other CIs, which may lead to undesirable behavior: https://github.com/facebook/react-native/issues/35547
[INTERNAL] [CHANGED] - Use `REACT_NATIVE_CI` instead of `CI` environment variable to trigger building Hermes from source on CircleCI.
`pod install` and `CI=true pod install` both consume Hermes prebuilt if available.
`REACT_NATIVE_CI=true pod install` builds Hermes from tag specified in `.hermesversion`.
CircleCI.

[LOCAL] fix: use REACT_NATIVE_CI instead of CI envvar

---

ReactCommon/ReactCommon.podspec

Following up [this comment](https://github.com/reactwg/react-native-releases/discussions/41#discussioncomment-4382407), this PR tries to fix the issue with `use_frameworks!` and the missing header.
[IOS] [FIXED] - Properly exclude files depending on the `use_frameworks!` option.
CircleCI should be green

[LOCAL] properly support both libraries and use_frameworks

---

.circleci/config.yml

(new variation of https://github.com/facebook/react-native/pull/35667, read [the last comment there](https://github.com/facebook/react-native/pull/35667#issuecomment-1357548196) for more info)
Because of the usual ✨dark magic✨ that we do 'cause RN is not a proper monorepo (usual link https://github.com/react-native-community/discussions-and-proposals/pull/480), one of the side effects is that `test_js` and `test_js_prev_lts ` insta-crash whenever they run in a `-stable` branch because of the `run_e2e` job, that runs verdaccio and verdaccio needs the workspace, but the workspace is not there because of the aforementioned ✨dark magic✨
This PR fixes that by not allowing said command to be run when we are in 0.XX-stable branches. (TIL that under the hood CircleCI wants [Java …

fix(CI): prevent the e2e test from running on 0.71

---

scripts/set-rn-version.js
scripts/test-e2e-local.js
scripts/version-utils.js

While working on this PR https://github.com/facebook/react-native/pull/35786 I encountered a problem in testing locally. Basically, I was getting hit by a silent error caused by recent work https://github.com/facebook/react-native/pull/35296 that didn't account for the shape of E2E local script for the release, `0.71.0-20230116-1649`.
This scripts fixes both aspects: the error now gets thrown "better" and the logic accounts for the E2E shape.
---
This is the PR for 0.71-stable branch, the one for main can be found here: https://github.com/facebook/react-native/pull/35846
[INTERNAL] [FIXED] - add logic for version scripts to account for local E2E test versioning
Tested in this PR; here's how it will error now:
and if you try running `yarn test-e2e-local -t RNTestProject -p Android` now it …

fix(scripts): add logic for version scripts to account for local E2E test versioning

---

scripts/react_native_pods.rb

Jokes aside, I think the breaking change was only introduced on the `0.71-stable` branch. So no need to fix anything on `main`.
[IOS] [FIXED] - Fix `pod install --project-directory=...`

fix(ios): fix `pod install --project-directory=...`

---

.circleci/config.yml
scripts/monorepo/__tests__/find-and-publish-all-bumped-packages-test.js
scripts/monorepo/bump-all-updated-packages/index.js
scripts/monorepo/constants.js
scripts/monorepo/find-and-publish-all-bumped-packages.js

Picking changes from https://github.com/facebook/react-native/pull/36146 and https://github.com/facebook/react-native/pull/36220 to have it in 0.71

Cherry-picking changes in CI scripts for packages versions bumping

---

packages/react-native/Libraries/Utilities/NativePlatformConstantsAndroid.js
packages/react-native/Libraries/Utilities/NativePlatformConstantsIOS.js
packages/react-native/Libraries/Utilities/Platform.android.js
packages/react-native/Libraries/Utilities/Platform.d.ts
packages/react-native/Libraries/Utilities/Platform.ios.js

This PR fixes some typings in the platform files. The `prerelease` value is actually a string as it can assume various values, not just numbers. We typically use `rc.W`, where only `W` is a number, but for local testing, for example, we use completely different strings.
[INTERNAL] [FIXED] - Use `?string` as `prerelease` type.
- CircleCI must be green on the job that were failing for this problem.

Fix platform Typings

---

packages/react-native/package.json
yarn.lock

This PR is part of the work @huntie is doing to fix the CLI-Metro situation. For the time being, this local commit should bring back CircleCI to a green state.
[General][Fixed] - Downgrade CLI to alpha.0 to make Metro work again
- CircleCI must be green

Downgrade CLI to `alpha.0` to get Metro working again in CI

---

yarn.lock

A continuation of https://github.com/facebook/react-native/pull/36654, but fixing the `localhost` references in the lockfile for compatibility externally.

[0.72-stable] Fix localhost references in yarn.lock

---

packages/react-native/Libraries/Core/ReactNativeVersionCheck.js

Before 0.72, a change landed that enforced the version to have a `number` as prerelease version (https://github.com/facebook/react-native/commit/8a59153bd7325055dcca33571ee0484f8f00fb30). 
However, this breaks the CI when we prepare the releases in OSS. This PR restore that possibility. 
[INTERNAL] [FIXED] - Restore Prerelease as string for OSS
- CircleCI must be green

Restore object with prerelease as string to unblock 0.72

---

package.json
packages/metro-config/index.js
packages/metro-config/package.json

As noted by @hoxyq [here](https://github.com/reactwg/react-native-releases/discussions/54#discussioncomment-5490653) there's some inconsistencies with what happened with metro config and its releases.
Basically, it looks like 0.72.1 of metro-config was released from main branch instead of 0.72-stable, which means that currently 0.72 is in an inconsistent state for [its package](https://github.com/facebook/react-native/blob/0.72-stable/packages/metro-config/package.json#L3).
Relevant commits:
* for 0.72-stable https://github.com/facebook/react-native/commit/9ffe82edd3f0a891b2421b34327d2859d3f5abdf
* for main https://github.com/facebook/react-native/commit/c5a47abaf894235f71eea03e57d2f5287d80f3d4#diff-cbcd5b7d5c2dff9dbd901bc385916ed457d12cfcdf9c2ed16bb44d18bb49232f
It shouldn't be too big …

fix(metro-config): fix and realign the situation for metro config for 0.72

---

.circleci/config.yml
scripts/cocoapods/__tests__/codegen_utils-test.rb
scripts/cocoapods/codegen_utils.rb

A quick attempt at a minimal fix for 0.70 for https://github.com/facebook/react-native/issues/36739, based on https://github.com/facebook/react-native/pull/36759
[IOS] [FIXED] - Fix React Codegen podspec to build on Xcode 14.3

fix(xcode): backport Xcode 14.3 fix to 70

---

.circleci/config.yml
scripts/cocoapods/__tests__/codegen_utils-test.rb
scripts/cocoapods/codegen_utils.rb

A quick attempt at a minimal fix for 0.71 for https://github.com/facebook/react-native/issues/36739, based on https://github.com/facebook/react-native/pull/36759
[IOS] [FIXED] - Fix React Codegen podspec to build on Xcode 14.3

fix(xcode): backport Xcode 14.3 fix to 71

---

.circleci/config.yml
packages/rn-tester/Podfile
scripts/react_native_pods.rb

A quick attempt at a minimal fix for 0.69 for https://github.com/facebook/react-native/issues/36739, based on https://github.com/facebook/react-native/pull/36759
[IOS] [FIXED] - Fix React Codegen podspec to build on Xcode 14.3

fix(xcode): backport Xcode 14.3 fix to 69

---

ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextUpdate.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java

This PR takes care of backporting the [needed commits](https://github.com/reactwg/react-native-releases/discussions/61#discussioncomment-5512273) for the textinput samsung issue to 0.71 stable.
I had a couple of merge conflicts to address, for commit https://github.com/facebook/react-native/commit/b9e2627d1ce64e8e293e90f743bf13a515db3b4d and commit https://github.com/facebook/react-native/commit/92b898149956a301a44f99019f5c7500335c5553, but they were relatively easy to address so I really hope it'll be easy to merge it.
Let's make sure to **NOT** squash and merge this when merging, so that we can keep all the separate commit references.
[ANDROID] [FIXED] - backporting of fixes for next 0.71 patch release
Test in RNTester that the textinput component page all works ok.

fix(textinput): backporting of fixes for next 0.71 patch release

---

ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextUpdate.java
ReactAndroid/src/main/java/com/facebook/react/views/text/TextLayoutManagerMapBuffer.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/BUCK
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java
ReactCommon/react/renderer/components/text/ParagraphState.h
ReactCommon/react/renderer/components/text/conversions.h
ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputState.cpp
ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputState.h

This PR takes care of backporting the [needed commits](https://github.com/reactwg/react-native-releases/discussions/62#discussioncomment-5519482) for the textinput samsung issue to 0.70 stable.
I had a couple of merge conflicts to address:
* for commit https://github.com/facebook/react-native/commit/b9e2627d1ce64e8e293e90f743bf13a515db3b4d, it was fairly straightforward
* for commit https://github.com/facebook/react-native/commit/92b898149956a301a44f99019f5c7500335c5553, I had to cherry pick this extra commit: https://github.com/facebook/react-native/commit/04c75ba988bf600f21f637120fca1a16835d80c9
Let's make sure to **NOT** squash and merge this when merging, so that we can keep all the separate commit references.
[ANDROID] [FIXED] - backporting of fixes for next 0.70 patch release
Test …

fix(textinput): backporting of fixes for next 0.70 patch release

---

ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java

Hopefully, third time's the charm (attempt 1: https://github.com/facebook/react-native/pull/36876, attempt 2: https://github.com/facebook/react-native/pull/36929).
This PR takes care of backporting the [needed commits](https://github.com/reactwg/react-native-releases/discussions/62#discussioncomment-5519482) for the textinput samsung issue to 0.69 stable.
I've only hit one minor merge conflict on for commit https://github.com/facebook/react-native/commit/b9e2627d1ce64e8e293e90f743bf13a515db3b4d, it was fairly straightforward.
As you might have noticed, this one misses the 9/9 commit and that's because it's not strictly necessary for the main fix - this was discussed with @NickGerleman.
[ANDROID] [FIXED] - backporting of fixes for next 0.69 patch release
Can't test RNTester Android …

fix(textinput): backporting of fixes for next 0.69 patch release (V3)

---

scripts/test-manual-e2e.sh

This PR fixes the same issues as [this](https://github.com/facebook/react-native/pull/36703) one for `main` did.
[INTERNAL] [FIXED] - Use packaged react-native in test-e2e-local script
Run `./scripts/test-manual-e2e.sh` for `RNTestProject` –> this script should succeed.

Fix test e2e script

---

ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java
scripts/test-manual-e2e.sh

This PR takes care of backporting the [needed commits](https://github.com/reactwg/react-native-releases/discussions/62#discussioncomment-5519482) for the textinput samsung issue to 0.68 stable.
If follows the exact same strategy used for the 0.69 version: https://github.com/facebook/react-native/pull/37000 plus adds the commit from Marek to fix e2e local testing script.
Let's make sure to **NOT** squash and merge this when merging, so that we can keep all the separate commit references.
[ANDROID] [FIXED] - backporting of fixes for next 0.68 patch release
Test in RNTester that the textinput component page all works ok.

fix(textinput): backporting of fixes for next 0.68 patch release

---

packages/react-native/scripts/cocoapods/jsengine.rb

We forgot to pass the file to the read function............ 🤦 
[IOS] [FIXED] - Pass the file name to the `read()` in jsengine.rb
Tested locally while testing the release

Pass the file that needs to be read

---

.circleci/Dockerfiles/Dockerfile.android
.circleci/config.yml

As we removed Buck OSS from `main`, you'll probably start seing both `test_buck` and `test_android_docker_image` failing.
This is happening as we started using language features which were not supported by Buck OSS (i.e. Java 8 lambdas) so cherry-picks could cause the CI to fail. This effectively removes the `buck` commands also from the release branches.
Pick one each for the category and type tags:
[INTERNAL] - [LOCAL] Do not run Buck OSS on release branches
CI Should be green

[LOCAL] Do not run Buck OSS on release branches

---

packages/react-native/Libraries/StyleSheet/StyleSheetTypes.d.ts
packages/react-native/types/experimental.d.ts

Pick https://github.com/facebook/react-native/commit/f9bf14d09d70fb89f7425c6c7f99aec96cbb2bf8 into 72 branch and remove the inset props that we reverted on 0.72
Verified on a local 72 project that instructions for enabling experimental types works.

Create experimental TS types

---

packages/react-native/Libraries/Lists/__tests__/__snapshots__/FlatList-test.js.snap
packages/react-native/Libraries/Lists/__tests__/__snapshots__/SectionList-test.js.snap
packages/rn-tester/js/components/ListExampleShared.js
packages/rn-tester/js/examples/FlatList/FlatList-basic.js
packages/rn-tester/js/examples/FlatList/FlatList-multiColumn.js
packages/rn-tester/js/examples/SectionList/SectionList-scrollable.js
packages/virtualized-lists/Lists/VirtualizedList.js
packages/virtualized-lists/Lists/__tests__/VirtualizedList-test.js
packages/virtualized-lists/Lists/__tests__/__snapshots__/VirtualizedList-test.js.snap
packages/virtualized-lists/Lists/__tests__/__snapshots__/VirtualizedSectionList-test.js.snap

Cherry picks the following onto 0.72-stable:
- https://github.com/facebook/react-native/pull/36844
- https://github.com/facebook/react-native/pull/35993
--

[0.72] Cherry pick - VirtualizedList fixes

---

packages/react-native/template/android/app/build.gradle

I've looked through the upgrade helper for 0.72 and noticed that we added a license header to `android/app/build.gradle` which should be reverted. This is a byproduct of the monorepo work as those files were excluded from the license header linter.
The equivalent change on main is:
- https://github.com/facebook/react-native/pull/37513
[INTERNAL] - Remove license header from android/app/build.gradle
Nothing to test

[LOCAL] Remove license header from android/app/build.gradle

---

packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/JdkConfiguratorUtils.kt

This is a fix for https://github.com/reactwg/react-native-releases/discussions/54#discussioncomment-5984629
It sets `kotlin.jvm.target.validation.mode=warning` so that projects won't break if they're using Kotlin 1.8+ and have JDK versions misaligned due to external libraries.
This doens't need to be backported to `main` as on main we set `jvmToolchain(11)` for all the libraries so this flag is unnecessary.
Also this is not a `.0` blocker and can land in `.1`
Also this requires a bump of RNGP
[INTERNAL] - Set kotlin.jvm.target.validation.mode=warning on user projects
Tested locally with `./gradlew build`.

[LOCAL] Set kotlin.jvm.target.validation.mode=warning on user projects

---

Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js
Libraries/Components/TextInput/TextInput.js
Libraries/Components/TextInput/__tests__/TextInput-test.js
Libraries/Components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Libraries/Components/View/View.js
Libraries/Components/View/__tests__/View-test.js
Libraries/Image/Image.android.js
Libraries/Text/Text.js
Libraries/Text/__tests__/Text-test.js

This cherry-picks https://github.com/facebook/react-native/pull/35316 for the next 0.71 stable patch.
[General][Added] - Added CSS logical properties by mapping layout props.

Add web compat unit tests and fixes

---

scripts/cocoapods/__tests__/codegen_utils-test.rb
scripts/cocoapods/codegen_utils.rb

`pod install --project-directory=ios` currently fails when new arch is enabled: https://github.com/react-native-async-storage/async-storage/pull/910
[IOS] [FIXED] - Fix `pod install --project-directory=...` when New Arch is enabled
```
git clone https://github.com/react-native-async-storage/async-storage.git
cd async-storage
gh pr checkout 910
yarn
RCT_NEW_ARCH_ENABLED=1 pod install --project-directory=example/ios
```

fix(ios): fix `pod install --project-directory=ios` failing

---

React/Base/RCTJavaScriptLoader.mm
React/CxxBridge/RCTCxxBridge.mm

**This is a pick of https://github.com/facebook/react-native/pull/37501 into 0.69-stable**
Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/37501
This is the iOS side of the fix for https://github.com/facebook/react-native/issues/36794.
That issue aside for the moment, the high-level idea here is to conceptually separate the bundle *request URL*, which represents a request for the *latest* bundle, from the *source URL* passed to JS engines, which should represent the code actually being executed. In future, we'd like to use this to refer to a point-in-time snapshot of the bundle, so that stack traces more often refer to the code that was actually run, even if it's since been updated on disk (actually implementing this isn't planned at the moment, but it helps …

[0.69] Use `Content-Location` header in bundle response as JS source URL (#37501)

---

packages/react-native/ReactAndroid/src/main/jni/react/jni/CatalystInstanceImpl.cpp
packages/react-native/ReactCommon/cxxreact/CMakeLists.txt
packages/react-native/ReactCommon/cxxreact/Instance.cpp
packages/react-native/ReactCommon/cxxreact/React-cxxreact.podspec

Cherry-pick of 0542da1aca5d411964e3a0833f4c48428ed90c91 to the 0.72 branch
Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/38125
On Android, when using the remote debugging feature (using legacy websockets), it's not safe to assume we can get a `jsi::Runtime` from `JSExecutor`.
Changelog: [General][Fixed] Android does't crash when using remote debugger
Reviewed By: NickGerleman
Differential Revision: D47124234
fbshipit-source-id: 0542da1aca5d411964e3a0833f4c48428ed90c91

Do not create RuntimeExecutor on non-JSI executors (#38125)

---

scripts/circle-ci-artifacts-utils.js
scripts/npm-utils.js
scripts/release-utils.js
scripts/test-e2e-local-clean.js
scripts/test-e2e-local.js
scripts/testing-utils.js
scripts/update-template-package.js

Cherry picking https://github.com/facebook/react-native/commit/f6197cd8469ffcdb68b46d1ff95b6ae079b6b829 to speedup release testing.
[internal] - cherry picking improved testing script
tested locally

Port CircleCI Artifact downloads to speed up release testing to 0.72

---

packages/react-native/Libraries/ReactNative/AppContainer.js

Cherry-picking https://github.com/facebook/react-native/pull/38727 into 0.72

fix[AppContainer]: mount react devtools overlay only when devtools are attached

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java
packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/FabricUIManagerTest.kt
packages/react-native/ReactAndroid/src/test/java/com/facebook/testutils/fakes/FakeBatchEventDispatchedListener.kt
packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/component/MyLegacyViewManager.java

Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/38527
This fixes a bug that got reported for the Fabric Interop for Android with Command dispatching. (See https://github.com/terrylinla/react-native-sketch-canvas/issues/236)
The problem is that libraries that were receiving commands as ints with:
```
public void receiveCommand(
int surfaceId, int reactTag, int commandId, Nullable ReadableArray commandArgs) {
```
would not receive command with the Fabric Interop for Android.
The problem is that with Fabric, events are dispatched as string always. cipolleschi took care of this for iOS, but we realized that the Android part was missing. I'm adding it here.
The logic is, if the event is dispatched as a string that represents a number (say `"42"`) and the user has …

[LOCAL] Fabric Interop - Properly dispatch integer commands (#38527)

---

packages/react-native/ReactAndroid/src/test/java/com/facebook/testutils/shadows/ShadowSoLoader.kt

JVM Tests for 0.72 are failing to compile due to a missing `ShadowSoLoader` class which exists in main. I'm adding it here.
[INTERNAL] - [LOCAL] Fix broken Android tests for 0.72
Tests are green locally, so should they be on CI

[LOCAL] Fix broken Android tests for 0.72

---

Libraries/ReactNative/AppContainer.js

Same as https://github.com/facebook/react-native/pull/38727, but removed references to TraceUpdatesOverlay

fix: mount devtools overlay only if react devtools are connected

---

React/Base/RCTBundleURLProvider.h
React/Base/RCTBundleURLProvider.mm
packages/rn-tester/Podfile.lock
packages/rn-tester/RNTesterUnitTests/RCTBundleURLProviderTests.m

Cherry-pick of #37878 to 0.71-stable
[IOS] [ADDED] - Added support to inline the source map via RCTBundleURLProvider

[0.71] Allow RCTBundleURLProvider to request an inline source map

---

package.json
scripts/monorepo/bump-all-updated-packages/bump-utils.js
scripts/monorepo/bump-all-updated-packages/index.js
scripts/publish-npm.js
scripts/trigger-react-native-release.js

One of the limitations of the existing flow for the release crew is that they need to manually remember to publish all the other packages in the monorepo ahead of a new patch release - this PR modifies the logic for the bump-oss-version script (and makes it available via yarn) so that it will not run if:
* there are git changes lying around
* if some of the packages need a new release
it required a bit of refactoring to extract some portions of the logic from the bump-all-package-versions script, but I think the end result is pretty decent.
This PR is the follow up from the one in main https://github.com/facebook/react-native/pull/38666 (plus https://github.com/facebook/react-native/pull/38887), and the one in 72 (https://github.com/facebook/react-native/pull/38888) to align the logic and …

chore(releases): improve bump oss script to allow less human errors (71 edition)

---

.circleci/config.yml
scripts/circleci/poll-maven.js

This local change adds a script to poll Maven automatically after the release has happened.
This should allow the Release Crew not to repeatedly and manually refresh Maven urls in order to see whether the artifacts are there or not.
As soon as this job is green, artifacts are out!
Cost wise, we are using a small machine, which costs 5 credits per minute.
[Internal] -Add script and CI job to poll for maven after a release.
Tested locally, running the JS script.
[Verified that the CI job can execute it](https://app.circleci.com/pipelines/github/facebook/react-native/29634/workflows/5966d5f9-12ca-40b1-9185-758fe98d3aee/jobs/944107).
We can only test this for real while doing a proper release.

[LOCAL] Add script poll maven

---

package.json
scripts/monorepo/bump-all-updated-packages/bump-utils.js
scripts/monorepo/bump-all-updated-packages/index.js
scripts/publish-npm.js
scripts/trigger-react-native-release.js

One of the limitations of the existing flow for the release crew is that they need to manually remember to publish all the other packages in the monorepo ahead of a new patch release - this PR modifies the logic for the bump-oss-version script (and makes it available via yarn) so that it will not run if:
* there are git changes lying around
* if some of the packages need a new release
it required a bit of refactoring to extract some portions of the logic from the bump-all-package-versions script, but I think the end result is pretty decent.
This PR is the follow up from the one in main https://github.com/facebook/react-native/pull/38666 (plus https://github.com/facebook/react-native/pull/38887) to align the logic and new command convention.
It's not urgent, can be merged after patch …

chore(releases): improve bump oss script to allow less human errors (72 edition)

---

packages/react-native/package.json
yarn.lock

This deduplicates Metro package versions at 0.76.8 and 0.76.7 following https://github.com/facebook/react-native/commit/40ea8ffcc7ba3ed0969405e9a48b75d188487d92

Bump CLI to 11.3.7

---

scripts/testing-utils.js

When testing another feature, I realized that we were not copying the `hermes-engine.podspec` and the `hermes-utils.rb` files from the `hermes-engine` folder to the `hermes` one.
This means that the script was building Hermes for local testing using an outdated `hermes-engine.podspec` that is downloaded from the `hermes` repo. 
[INTERNAL] - Copy over the `hermes-engine.podspec` and `hermes-utils.rb` files in the `test-e2e-local` script
Tested locally

[LOCAL] Copy hermes ruby files to hermes folder in local E2E test

---

packages/normalize-color/package.json

Intends to resolve #39692 once published.
We believe this bug is caused by a `"*"` version specifier for the `@react-native/normalize-color` package inside the `deprecated-react-native-prop-types` dependency.
https://github.com/facebook/react-native-deprecated-modules/blob/b34e786d1566d8ef2459875d51388d0e6b1ac399/deprecated-react-native-prop-types/package.json#L8
**Changes**
- Fixes the above issue in `@react-native/normalize-color`.
- This **removes** the `"node": ">=18"` `engines` constraint. This is to be as lenient as possible for this hotfix, where the Node version should already be suitably constrained by other deps in a 0.72 project. (We will restore this constraint if/when we align versioning in `deprecated-react-native-prop-types` — or remove this package from the dependency …

[0.73] Hotfix: Remove node engines constraint for normalize-color

---

.circleci/configurations/workflows.yml

Same issue of the previous fix: jobs do not run by default on tagged build. I forgot to add the `filter` parameter in the jobs that build the slices for Hermes and packages it and therefore the build failed.
I added those filters, so now we should be able to release RC.1.
What puzzles me is how it is possible that the `publish-npm` jobs even started, given that it was set up to depends on a job called `build_hermes_macos` which was not executed in the pipeline. 🤔  
[Internal] - Make sure that the Hermes jobs starts when releasing
We can't really test this changes until we make a release.

[RN[CI] Makes the Jobs required for Hermes to run in tagged build while releasing 

---

packages/react-native/React/UIUtils/RCTUIUtils.h

Back port of https://github.com/facebook/react-native/commit/f174f028cfae29735e3f04ad5f42079b67658642 to 0.73-stable, so we can remove the method altogether for 0.74+.
Original notes:
> Per https://github.com/facebook/react-native/pull/39617#issuecomment-1734330041 , let's deprecate this method first.
[IOS] [DEPRECATED] - Deprecate RCTGetMultiplierForContentSizeCategory
CI should pass

[iOS] Deprecate RCTGetMultiplierForContentSizeCategory

---

.gitignore
Gemfile
Gemfile.lock
packages/react-native/scripts/cocoapods/utils.rb
packages/rn-tester/Podfile.lock

This change should fix the CI and make sure we have the right fixes for ActiveSupport and Xcode 15
[Internal] - Fix CI

[Local] Fix CI for 0.72, with Acitve Support and Xcode15

---

.circleci/config.yml

Instruction to install node on Debiam machine [has changed](https://github.com/nodesource/distributions#new-update-%EF%B8%8F) and the previous script cannot be used anymore.
This change updates it.
[Internal] - Fix CI

[RN][CI]Update node installation on debian (0.72) 

---

.circleci/config.yml
.circleci/configurations/jobs.yml

Instruction to install node on Debiam machine [has changed](https://github.com/nodesource/distributions#new-update-%EF%B8%8F) and the previous script cannot be used anymore.
This change updates it.
[Internal] - Fix CI

[RN][CI]Update node installation on debian (0.73)

---

packages/react-native/package.json
yarn.lock

In this version we fixed the performance issue when running `run/build-android` commands. https://github.com/react-native-community/cli/pull/2145
[GENERAL] [CHANGED] - Bump CLI to v11.3.10
CI

Bump CLI to v11.3.10

---

packages/react-native/ReactCommon/react/renderer/components/legacyviewmanagerinterop/LegacyViewManagerInteropComponentDescriptor.mm
packages/react-native/ReactCommon/react/renderer/components/legacyviewmanagerinterop/RCTLegacyViewManagerInteropCoordinator.mm

Cherry-pick of https://github.com/facebook/react-native/commit/daedbe6e3e4cb4b5fde533bf8205edd89a18c480.
Created a PR as the commit caused merge conflicts in the 0.72-stable branch.
[iOS][Fixed] - Add support for Components with custom names in the interop layer.
See: https://github.com/facebook/react-native/pull/41207

Make the interop-layer work with components with custom name

---

scripts/circle-ci-artifacts-utils.js
scripts/test-e2e-local.js
scripts/testing-utils.js

Cherry pick of https://github.com/facebook/react-native/commit/4eed12b7df5d9731e556b77d701c87dcf91d3a1f. Doing a PR due to merge conflicts.
[Internal] - Fix Android E2E test script when downloading artefacts from CI
See test plan in https://github.com/facebook/react-native/pull/41172

Fix RNTestProject testing on Android

---

packages/react-native/Libraries/LogBox/Data/LogBoxData.js
packages/react-native/Libraries/promiseRejectionTrackingOptions.js

Cherry pick of https://github.com/facebook/react-native/commit/18c9797ecc8dab220ec68aae011ddb73db17a99d. Doing a PR due to merge conflicts.
[GENERAL] [FIXED] - Show correct stack frame on unhandled promise rejections on development mode.
See test plan in https://github.com/facebook/react-native/pull/40914

Symbolicate unhandled promise rejections

---

packages/community-cli-plugin/package.json
packages/react-native/cli.js
packages/react-native/package.json
yarn.lock

Updates CLI. Also I provided `platformName` parameter to `run()` function when executing CLI.
[GENERAL] [CHANGED] - Bump CLI to v12.1.1
CI Green

Update CLI to v12.1.1

---

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm

In the codebase, we never set the `RCT_USE_HERMES` flag.
When we [install the pods](https://github.com/facebook/react-native/blob/b4d4aef057ebf90176287f22d72b4b3b8b280c9a/packages/react-native/scripts/react_native_pods.rb#L76), we use the `USE_HERMES` flag and we [set `USE_HERMES`](https://github.com/facebook/react-native/blob/b4d4aef057ebf90176287f22d72b4b3b8b280c9a/packages/react-native/scripts/cocoapods/utils.rb#L69) as a build setting. So, the `RCT_USE_HERMES` flag will always be not set for the OSS.
[iOS][Fixed] - Use the right `USE_HERMES` flag
Revert Hammer

Revert "RNTester-ios / RCTAppDelegate > correctly check for USE_HERMES Flag"

---

packages/react-native/ReactCommon/react/renderer/imagemanager/platform/ios/React-ImageManager.podspec
packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb
packages/react-native/scripts/cocoapods/codegen_utils.rb

This is the porting of #41640 to 0.73
`react-native-svg` reported that the SVG library was not building on the latest RC of React Native because Codegen was not finding the proper files.
By inspecting an example app with SVG, we realized that React-Codegen was not depending on `React-FabricImage`, while having access to their headers.
We added the dependency, but them the build was failing due to a circular dependency because the `React-ImageManager` was dependeing on `React-RCTImage`.
This dependency is conceptually wrong (a piece of Core should not depend on Library which depends on Core... 😑) and I verified that by removing that dependency the framework continue to build.
[Internal] - Fixed dependencies of Codegen on React-Image
Tested on a local app + CircleCI

[RN][iOS] Fix React-FabricImage dependencies

---

packages/react-native-gradle-plugin/build.gradle.kts
packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactRootProjectPlugin.kt
packages/react-native/template/android/build.gradle

This is a pick of #41621 on the release branch
[Android] [Fixed] - Fix projects being broken on dependencies starting with `a..`
n/a

[0.73] Fix projects being broken on dependencies starting with `a..`

---

packages/react-native-codegen/package.json

In pnpm setups, codegen will fail during build because it cannot find its dependencies. Some of the dependencies it relies on at runtime are currently declared under `devDependencies`. This change moves them to `dependencies`.
Cherry-picks c58e19e89aadcc01c2ac8ead876831ed8a2f6c5d.
[GENERAL] [FIXED] - Fix `react-native/codegen` not being able to resolve dependencies in pnpm setups
We are currently trying to [enable pnpm mode](https://github.com/microsoft/rnx-kit/pull/2811) in rnx-kit and hit this issue. We've patched this package locally and it works.

Correctly declare runtime dependencies

---

packages/react-native/scripts/cocoapods/__tests__/codegen-test.rb
packages/react-native/scripts/cocoapods/codegen.rb

`build_codegen!` currently assumes that `@react-native/codegen` gets installed next to `react-native`. In a pnpm setup, it's found under `/~/react-native/node_modules/@react-native/codegen` instead.
However, as @dmytrorykun pointed out, we don't actually need to build it outside of this repository.
Cherry-picks https://github.com/facebook/react-native/commit/3dd6a83c0e39c54b4ff050589e4e13f1ccc66a5d
[GENERAL] [FIXED] - `@react-native/codegen` shouldn't be built unless it's in the repo — fixes `pod install` failures in pnpm setups
We have a patched version of `react-native` working in a pnpm setup here: https://github.com/microsoft/rnx-kit/pull/2811

Fix `build_codegen!` not finding `@react-native/codegen` in pnpm setups

---

.circleci/config.yml
packages/react-native/Libraries/LogBox/Data/parseLogBoxLog.js
packages/react-native/flow-typed/npm/ansi-regex_v5.x.x.js
packages/react-native/package.json
packages/rn-tester/Podfile.lock

Cherry pick of: https://github.com/facebook/react-native/pull/38005
Going through a PR due to merge conflicts.
[GENERAL][FIXED] Prevent LogBox from crashing on very long messages

Prevent LogBox from crashing on long messages (#38005)

---

.circleci/config.yml

Instruction to install node on Debiam machine [has changed](https://github.com/nodesource/distributions#new-update-%EF%B8%8F) and the previous script cannot be used anymore.
This change updates it.
[Internal] - Fix CI

[RN][CI]Update node installation on debian (0.71) 

---

scripts/cocoapods/__tests__/utils-test.rb
scripts/cocoapods/utils.rb

- Fix overriding `EXCLUDED_ARCHS` when installing Hermes on RN v0.71
- Extract the logic and the tests from `main`
Recommended to create a pull request against `0.71.stable` [here](https://github.com/reactwg/react-native-releases/discussions/87#discussioncomment-7141691) 
ref: https://github.com/facebook/react-native/pull/39060
[IOS] [FIXED] - don't override EXCLUDED_ARCHS when installing Hermes
Tests pass

Fix overriding `EXCLUDED_ARCHS` when installing Hermes on RN v0.71

---

.circleci/configurations/commands.yml

`test_e2e_ios` is failing because the default bundler version that is installed in CI does not support Ruby 2 anymore.
This PR ports the same fix @fortmarek did for 0.72 in #41989
[Internal] - Fix test_e2e_ios in CI

[RN][CI] Fix e2e test setup

---

packages/babel-plugin-codegen/package.json
packages/eslint-plugin-specs/package.json
packages/react-native-babel-preset/package.json
packages/react-native-babel-transformer/package.json
packages/react-native-codegen-typescript-test/package.json

See description in https://github.com/facebook/react-native/pull/42081
Applying those same changes to 0.73 branch but using latest updated versions of those packages. Before merging we should ensure the monorepo deps are using the latest 0.73.x version.
[GENERAL] [CHANGED] - Remove * dependencies on monorepo packages in 0.73. 
Verified that these will now be included in the bump and align process when we update monorepo packages
https://github.com/facebook/react-native/blob/2f92a87e4385d515f718479005c623c04fa1bb83/scripts/monorepo/align-package-versions.js#L39-L63

Update these to use latest 0.73.x versions

---

ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java
ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagersPropertyCache.java
packages/rn-tester/Podfile.lock

Cherry-picks the following:
- https://github.com/facebook/react-native/pull/41478
- https://github.com/facebook/react-native/pull/41277 
- https://github.com/facebook/react-native/pull/39763 
- https://github.com/facebook/react-native/commit/265af222aa8acb3b514e22a7db191d66755f553b
- https://github.com/facebook/react-native/commit/94972039571e1f3b387e0f63227a6ad13740eaf3
[ANDROID][FIXED] Fix android platform border color
[ANDROID][FIXED] Android: fix ClassCastException in ReactRootView.java when software keyboard is shown
[GENERAL][CHANGED] Bump podfile.lock
CI

chore: cherry picks for 0.71.15

---

packages/babel-plugin-codegen/package.json
packages/eslint-plugin-specs/package.json

Pin the versions of monorepo deps such that we don't accidentally pull updated monorepo libs as we don't follow semver. A patch may not be backwards compat
Note: This change has also been applied to 72, 73, and main. I'm not sure this makes that much sense in 71 as we don't have a lot of monorepo deps set up yet.
[GENERAL] [CHANGED] - Pin monorepo deps - react-native-codegen
n/a

Fix react-native-codegen

---

packages/react-native/ReactCommon/react/renderer/core/PropsParserContext.h

`React-Fabric` fails to build because implicit constructors are no longer generated.
```
❌ /~/example/ios/Pods/Headers/Public/React-Fabric/react/renderer/core/RawPropsParser.h:50:24: no matching constructor for initialization of 'PropsParserContext'
PropsParserContext parserContext{-1, contextContainer};
^            ~~~~~~~~~~~~~~~~~~~~~~
```
This was fixed in 0.73 here: https://github.com/facebook/react-native/commit/e1876af923647ff8c10057414cf502e40feafdc6#diff-696b8d801910a87b0ba34645cfefcf01238c3f670d0e956a274091a6c950cc12
[IOS] [FIXED] - `React-Fabric` fails to build with `-std=c++20` because implicit constructors are no longer generated
n/a

Fix New Arch build failing with `-std=c++20`

---

packages/react-native/ReactAndroid/build.gradle
packages/react-native/third-party-podspecs/boost.podspec

JFrog is down and it's making all the iOS build fails. Reference: #42110
[Internal] - Change url from where boost is downloaded
CI is green

[Local][RN][General] 0.72 - migrate boost away from JFrog

---

ReactAndroid/build.gradle
third-party-podspecs/boost.podspec

JFrog is down and it's making all the iOS build fails. Reference: #42110
[Internal] - Change url from where boost is downloaded
CI is green

[0.71][RN][General] Migrate boost download url away from JFrog

---

ReactAndroid/build.gradle
third-party-podspecs/boost.podspec

JFrog is down and it's making all the iOS build fails. Reference: #42110
[Internal] - Change url from where boost is downloaded
CI is green

[0.70][RN][General] Migrate boost download url away from JFrog

---

packages/react-native/scripts/cocoapods/utils.rb

While developing Xcode 15, Apple reimplemented the linker. 
In Xcode 15.0, the linker was making old iOS (< 15) crash when they were built using Xcode 15.
To fix that, we make Apple create new compiler flags (`-ld_classic`) to have a backward compatible linker.
In Xcode 15.1, Apple fixed that behavior, so the flags should not be required anymore. 
But now, if we pass `-ld_classic` to the linker and we have an app that is using `use_framworks!`, that app crashes at startup.
This change remove the flags if the Xcode that is used is 15.1 or greater.
*Note:* The previous change added the flags to Hermes as well. I tested this fix in a configuration where Hermes has the flags and React Native does not, and it works. So we are removing the flags only from React Native. 
[Internal] - Do not add …

[RN][iOS] Fix symbol not found _jump_fcontext with use_frameworks!

---

.circleci/config.yml
packages/react-native/sdks/hermes-engine/utils/build-apple-framework.sh

Backports the commit https://github.com/facebook/react-native/commit/de6bfec82a1cb4b387bfe8a87b1f597f39572764 to 0.72.
Disabling the Bitcode has several benefits:
1. Downloading artifacts while testing will take much less time
2. Creating a new app will take less time
3. The Space occupied on Dev's machine is sensibly smaller
Community testing reported that the tarball size get reduced from ~500 Mb to ~25 Mb, a x20 reduction
[iOS][Changed] - Disabled bitcode for Hermes prebuilts
Wait for CircleCI...

[RN][iOS] Disable Bitcode for Hermes

---

packages/react-native/React/Modules/RCTUIManager.m
packages/rn-tester/Podfile.lock

Community reported a race condition when 0.73 apps are built in Release mode. What happens is that there is a deadlock between the accessibility manager and the UIManager.
This PR fixes the deadlock by moving the accessibility manager lazy initialization.
[Internal] - Fixed deadlock at startup 
Tested in a 0.73 app

[RN][iOS] Fix race condition between A11yManager and UIManager

---

ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java

I'm cherry-picking 96ed1190c624869af96e464b009e0c0234076893 on the release branch for 0.71.
This change allows activities to handle onRequestPermissionsResult callbacks (eg: registerForActivityResult)
Fixes #42403
[Android][Changed] - Call super.onRequestPermissionsResult in ReactActivity's onRequestPermissionsResult()
Pull Request resolved: https://github.com/facebook/react-native/pull/42478
Test Plan:
**Without super.onRequestPermissionsResult() call**
**With super.onRequestPermissionsResult() call**

Cherry-picking 'Call super.onRequestPermissionsResult in ReactActivity (#42478)' onto 0.71

---

packages/rn-tester/Gemfile
packages/rn-tester/Podfile.lock
packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
template/Gemfile

Cherry Picking 3869ae4 on the release branch 0.71-stable. This fixes the issue https://github.com/facebook/react-native/issues/42698 for 0.71 projects.
[iOS][Fixed] don't allow cocoapods 1.15.
```
bundle exec pod install
```

Cherry-picking 'Avoid using Cocoapods 1.15 until it fixes an issue affection RN. (#42702)' onto 0.71

---

packages/react-native/React/Modules/RCTUIManager.m

When we fixed the race condition between A11yManager and RCTUIManager, we did it by moving the A11yManager on a background queue.
In the old architecture, this was raising a warning which our users might find confusing. Plus, that change was not aligned with what the A11yManager declared in its configuration because we are actually initializing it starting from a BG queue.
With this change we anticipate the initialization of the module in a place where:
1. We know we are in the main queue
1. We know we are going to need it (so it is not violating the lazy load principle)
1. We know it is safe.
This should allow us to also remove the feature flag of RCTUIManagerDispatchAccessibilityManagerInitOntoMain because now it is safe to use the main_queue as requested by the module.
[iOS][Fixed] - …

[RN][iOS] Fix warning when loading RCTUIManager and A11yManager

---

packages/community-cli-plugin/src/utils/loadMetroConfig.js

`@react-native/community-cli-plugin` is unable to resolve out-of-tree platforms in monorepos because the package may not be hoisted to the same location. For example, if `@react-native/community-cli-plugin` was hoisted:
```
/~/node_modules/@react-native/community-cli-plugin/dist/utils
```
It may never find `react-native-macos` if it wasn't hoisted:
```
/~/packages/my-app/node_modules/react-native-macos
```
[GENERAL] [FIXED] - Fix `@react-native/community-cli-plugin` is unable to resolve out-of-tree platforms in monorepos
Cherry-picks #42875

[LOCAL][0.73] fix: cannot find module `react-native-*/Libraries/Core/InitializeCore`

---

packages/react-native/ReactCommon/React-Fabric.podspec
packages/react-native/ReactCommon/react/debug/React-debug.podspec
packages/react-native/ReactCommon/react/renderer/graphics/React-graphics.podspec
packages/react-native/ReactCommon/react/utils/React-utils.podspec

We are suggesting and migrating 3rd party libs to use `install_modules_dependencies` in their podspecs.
However, when some of those libs uses Swift, they become incompatible with some of the pods we expose because we forgot to define modules in those libraries.
With these changes, they would be able to be installed correctly in a 0.72 react Native app.
[Internal] - Improve Swift support by defining modules in React-Fabric, React-graphics, React-utils and React-debug.
Tested locally by running:
```
npx react-native@0.72.7 init NewApp --version 0.72.7 --skip-install
cd NewApp
yarn add lottie-react-native
cd ios
bundle install
RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
open NewApp.xcworkspace
```
<kbd>⌘</kbd> + <kbd>B</kbd>
Observe the app failing to build.
Apply these changes:
``` …
```

[RN][iOS] Improve Swift support for 3rd party libs

---

packages/react-native/scripts/cocoapods/__tests__/utils-test.rb
packages/react-native/scripts/cocoapods/utils.rb

Created the same fix on RN v0.72 as the previous fix was only available on RN v0.71 https://github.com/facebook/react-native/pull/39763
No need to fix for RN v0.73.
ref
* https://github.com/facebook/react-native/pull/39060
* https://github.com/facebook/react-native/pull/38132
* https://github.com/facebook/react-native/pull/40656
[IOS] [FIXED] - don't override EXCLUDED_ARCHS when installing Hermes
Tests pass

Fix overriding EXCLUDED_ARCHS when installing Hermes on RN v0.72

---

packages/react-native/scripts/codegen/generate-artifacts-executor.js

`pod install` (and probably Android build as well) fails when New Architecture is enabled because the path to `@react-native/codegen` is hardcoded.
```
% pod install --project-directory=ios
Framework build type is static library
[Codegen] Adding script_phases to React-Codegen.
[Codegen] Generating ios/build/generated/ios/React-Codegen.podspec.json
[!] Invalid `Podfile` file: [!] node ios/../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /~/packages/test-app -o /~/packages/test-app/ios -e true -c
[Codegen] Processing react-native core libraries
[Codegen] Found react-native
[Codegen] >>>>> Searching for codegen-enabled libraries in /~/node_modules/.store/react-native-virtual-0bcd9fdafa/node_modules
[Codegen] >>>>> Searching for codegen-enabled libraries in …
```

fix: fix codegen not finding all third-party libraries

---

.circleci/configurations/jobs.yml
scripts/monorepo/__tests__/find-and-publish-all-bumped-packages-test.js
scripts/monorepo/find-and-publish-all-bumped-packages.js
scripts/monorepo/for-each-package.js
scripts/releases-ci/README.md
scripts/releases-ci/__tests__/publish-updated-packages-test.js
scripts/releases-ci/publish-updated-packages.js
scripts/releases/utils/monorepo.js

Cherry-picks the following updates to our `find_and_publish_bumped_packages` CI workflow onto the `0.73-stable` branch (Meta employees: stack beginning D53607809):
- #42936
- #42937
- #42938
- #42944
- #42964
- #42989
These changes should make `find_and_publish_bumped_packages` 1/ more reliable (built-in network retry), 2/ re-runnable (uses npm as source of truth, meaning it can be rerun from an incomplete previous attempt).
The script is renamed from `scripts/monorepo/find-and-publish-all-bumped-packages.js` to `scripts/releases-ci/publish-updated-packages`.

[0.73-stable] Cherry-pick improvements to monorepo publish script

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

Bump CLI version to 12.3.6
[GENERAL] [CHANGED] - Bump CLI to 12.3.6
CI

Update CLI to 12.3.6

---

scripts/e2e/init-template-e2e.js
scripts/release-testing/test-e2e-local.js

This PR fixes the release testing script:
* Fix typo in variable name for circleciToken arg.
* Relocate erroneously positioned process.exit call (a force exit around Verdaccio, which we will remove in future).
* Add notice on exit around Verdaccio server not being killed successfully 
* Move from yarn to npm as yarn v3 does not work well with verdaccio
[Internal] - Fix E2E testing script
Tested locally

[RN][Release] Fix release testing script

---

.circleci/configurations/executors.yml
.circleci/configurations/jobs.yml
packages/react-native/sdks/hermes-engine/hermes-utils.rb

In OSS we have reports like [this one](https://github.com/facebook/react-native/issues/43241) where env variables from different settings might clash together, making react native apps fail to build hermes.
For example, a team might have defined a BUILD_FROM_SOURCE env variable to build their specific project from source and that will clash with how react native apps installs Hermes.
This change disambiguate the BUILD_FROM_SOURCE flag we have internally, moving to a less likely to clash RCT_BUILD_HERMES_FROM_SOURCE.
[iOS][Breaking] - Rename BUILD_FROM_SOURCE to RCT_BUILD_HERMES_FROM_SOURCE
CircleCI

[RN][iOS]Rename BUILD_FROM_SOURCE to RCT_BUILD_HERMES_FROM_SOURCE

---

packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb
packages/react-native/scripts/cocoapods/new_architecture.rb

This commit backports to 0.72 [these changes](https://github.com/facebook/react-native/commit/929df582c885ad60bd34e52ced481f8e9d5666d9) we already shipped on main and on 0.73.
[iOS][Fixed] - Pass the right flags to libraries when the new arch is enabled
Ruby Tests and same changes released in previous versions which fixes the problem.

[RN][IOS] Fix flags for new arch

---

packages/react-native/scripts/cocoapods/utils.rb
packages/react-native/scripts/react_native_pods.rb
packages/rn-tester/Podfile.lock

Following https://github.com/facebook/react-native/issues/43335, we implemented the fix suggested [here](https://github.com/facebook/react-native/issues/43335#issuecomment-1980708164).
The rationale of applying this fix rather then releasing a new version of Flipper is because we will have to release Flipper `0.248.0`, and the latest flipper version on Cocoapods is `0.233.0` (15 versions behind).
Plus, we have to backport the fix to 0.72 and 0.71 and bumping Flipper there would be a major pain and it might require more time and introduce other bugs we don't want.
[iOS][Fixed] - Make 0.73 build with Xcode 15.3
Tested locally + CircleCI is green

[RN][iOS] Fix flipper for Xcode 15.3

---

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.h
packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.mm

cherry-pick RCTRootViewFactory regression fix to 0.74-stable branch, that to follow up [this](https://github.com/facebook/react-native/pull/43526#issuecomment-2014954813).
- https://github.com/facebook/react-native/commit/9d79f05e
- https://github.com/facebook/react-native/commit/84c1c6ea
[IOS] [FIXED] - add missing forward blocks to RCTRootViewFactory
ci passed

fix(iOS): add missing forward blocks to RCTRootViewFactory

---

packages/react-native/ReactAndroid/build.gradle.kts
packages/react-native/ReactAndroid/hermes-engine/build.gradle.kts

The instructions to build from source are not working in 0.74 RC. This fixes it.
[ANDROID] [FIXED] - Fixes build from source on Android
Tested locally

[0.74] Fixes build from source on Android

---

packages/react-native/React/Base/RCTBridge+Inspector.h
packages/react-native/React/Base/RCTBridge+Private.h
packages/react-native/React/Base/RCTBridge.mm
packages/react-native/React/CoreModules/RCTDevSettings.mm
packages/react-native/React/CxxBridge/RCTCxxBridge.mm
packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.mm

new debugger logic added in 0.74 implicitly imported a C++ library depending on boost into the public headers for anyone importing RCTBridge+Private, which is a common header imported by libraries. boost is hard to link correctly, so this has caused issues with libraries such as OP-SQLite (https://github.com/facebook/react-native/issues/43204).
this must be picked directly against 0.74 instead of off master because PageTarget was renamed to HostTarget after the 0.74 cut.
do not pick into master!!!
build passes

[rn][ios][0.74][RC6] decouple RCTBridge+Private from jsinspector-modern

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

- Fixes `init` command when using older Yarn Classic versions: https://github.com/react-native-community/cli/pull/2329.
- https://github.com/react-native-community/cli/pull/2344
[GENERAL] [CHANGED] - Upgrade `@react-native-community/cli` to 13.6.4
CI

Upgrade `@react-native-community/cli` to 13.6.4

---

packages/rn-tester/Podfile.lock
scripts/cocoapods/utils.rb
scripts/react_native_pods.rb

Following https://github.com/facebook/react-native/issues/43335, we implemented the fix suggested [here](https://github.com/facebook/react-native/issues/43335#issuecomment-1980708164).
The rationale of applying this fix rather then releasing a new version of Flipper is because we will have to release Flipper `0.248.0`, and the latest flipper version on Cocoapods is `0.233.0` (15 versions behind).
Plus, we have to port the fix to 0.73 and 0.72 and bumping Flipper there would be a major pain and it might require more time and introduce other bugs we don't want.
[iOS][Fixed] - Make 0.71 build with Xcode 15.3
Tested locally + CircleCI is green

[RN][iOS][0.71] Fix flipper for Xcode 15.3

---

packages/react-native/ReactCommon/yoga/Yoga.podspec

Following up https://github.com/facebook/react-native/issues/41938, this PR targeting 0.74 will fix an archiving issue for the Yoga pod
[iOS][Fixed] - Fix Yoga archiving with static frameworks on MacOS Catalyst
Tested locally and by the community

[Yoga][0.74] Fix archive for MacOS Catalyst

---

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.h
packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.mm
packages/react-native/React/Base/RCTBridgeProxy.h
packages/react-native/React/Base/RCTBridgeProxy.mm
packages/react-native/ReactCommon/react/nativemodule/core/platform/ios/ReactCommon/RCTTurboModuleManager.mm
packages/react-native/ReactCommon/react/runtime/iostests/RCTHostTests.mm
packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTHost+Internal.h
packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTHost.h
packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTHost.mm
packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.h
packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.mm
packages/react-native/ReactCommon/react/test_utils/ios/Shims/ShimRCTInstance.h
packages/react-native/ReactCommon/react/test_utils/ios/Shims/ShimRCTInstance.mm
packages/rn-tester/Podfile.lock
packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj

This PR includes the Cherry picks for #43757 and #43994 which includes:
* supporting launchOptions in Bridgeless to enable RCTLinkingManager in Bridgeless, thus unblocking deep linking and universal links
* fix connection to Metro in bridgeless when the app is started before Metro.
[iOS][Fixed] - Support launchOptions in Bridgeless mode.
[iOS][Fixed] - Let RCTHost be initialized with a function to provide the `bundleURL` so that it can connect to metro on Reload when the url changes.
Landed on main already

[RN][iOS] Cherry Pick #43757 and #43994

---

packages/react-native/ReactCommon/yoga/Yoga.podspec

Following up #41938, this PR targeting 0.73 will fix an archiving issue for the Yoga pod
[iOS][Fixed] - Fix Yoga archiving with static frameworks on MacOS Catalyst
Tested locally and by the community

[Yoga][0.73] Fix archive for MacOS Catalyst

---

packages/rn-tester/PrivacyInfo.xcprivacy
packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
scripts/cocoapods/utils.rb
scripts/react_native_pods.rb
template/ios/HelloWorld.xcodeproj/project.pbxproj
template/ios/HelloWorld/PrivacyInfo.xcprivacy

Cherry pick of https://github.com/facebook/react-native/commit/d39712f54a95e6dcdf1d2f80d9581211ab03c157 and https://github.com/facebook/react-native/commit/520d120375c6b24bc161adea4f48d76537a34abc for privacy manifest
[iOS][Added] - Privacy manifest for 0.71
Tested locally on RNTester + CI must be green

[iOS][Privacy Manifest] Set up privacy manifest for React Native 0.71

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

New version contains a fix for not executing `packages/react-native/cli.js` file: https://github.com/react-native-community/cli/pull/2389.
[GENERAL] [CHANGED] - Upgrade `@react-native-community/cli` to `13.6.8`
CLI should be executed through `packages/react-native/cli.js`.

feat: upgrade CLI to `13.6.8`

---

.github/workflows/test-all.yml

This change bump the executors from 14 GB to 150 GB of space.
We are seeing many failures on Android due to the disk running out of space
[Internal] - Increase runner for Android_helloworld to avoid to run out of disk space
GHA are green

[LOCAL][RN][CI] Use bigger machines for Android Helloworld

---

.circleci/configurations/jobs.yml

This aligns the 0.75 release branch with main
[INTERNAL] - Disable test_js_e2e on the 0.75 release branch
See CI

[LOCAL] Disable test_js_e2e on the 0.75 release branch

---

scripts/release-testing/test-e2e-local.js

This changes update the release testing script to run with the community template rather than the template inside react-native
[Internal] - Update the testing script to run with the community template
Tested locally to test the release for 0.75.0-RC.0. See https://github.com/reactwg/react-native-releases/issues/325

[LOCAL][RN][Release Testing] Update the testing script to run with the community template

---

.github/actions/create-release/action.yml
.github/workflows/create-release.yml

This change forwards inputs from the github workflow Create Release to the composite action which encapsulate the logic
[Internal] - Forward inputs to Create Release composite action
Testing after merging

[LOCAL][CI][Release] Forward inputs to Create Release composite action

---

.github/actions/create-release/action.yml

This should unblock `git commit` on the release branch
[INTERNAL] - Configure git user before attempting to publish a release
NA

[LOCAL] Configure git user before attempting to publish a release

---

scripts/__tests__/npm-utils-test.js
scripts/npm-utils.js

This change fixes the publish-npm script. The documentation for `GITHUB_REF` and `GITHUB_REF_NAME` is [here](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables). Search for the two variables.
[Internal] - Fix Release scripts
Added a JS test + test in prod! 😄

[LOCAL][RN][CI] Fix release scripts to use GITHUB_REF and GITHUB_REF_NAME variables

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

New version contains a fix for correctly receiving android launch activities: https://github.com/react-native-community/cli/commit/a00f927b99e4925cdf54a7deb995db853e645fa8.
[GENERAL] [CHANGED] - Upgrade `@react-native-community/cli` to `13.6.9`
No plan.

feat: update CLI to 13.6.9

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

Bump CLI dependencies to `alpha.9`
[General][Changed] - Bump CLI dependencies to alpha.9
CI is green

[RN][CI] Bump react-native CLI dependency to alpha.9

---

.github/actions/cache_setup/action.yml
.github/actions/prepare-hermes-workspace/action.yml
.github/actions/restore-hermes-workspace/action.yml
.github/actions/test_ios_helloworld/action.yml
.github/workflows/nightly.yml
.github/workflows/publish-release.yml
.github/workflows/test-all.yml

Building MacOS slices is failing because the Hermes build script tries to read the version for MacOS by evaluating the `hermes-engine.podspec`. The Hermes script is actually executing the `podspec`.
However, the `podspec` relies on some constants that are defined in Cocoapods, but it is not explicitly depending on it. So, when executed without a cocoapods command, like we are doing in the hermes build scripts, it fails.
To solve this, we are adding cocoapods as an explicit dependency of the `podspec`
[Internal] - Add explicit dependency to cocoapods in hermes-engine.podspec
GHA should be green.

[LOCAL][CI] Require cocoapods to hermes-engine podspec

---

scripts/e2e/init-template-e2e.js
scripts/release-testing/test-e2e-local.js

This PR applies changes to the testing script for releases so that it can use the new template and the new react-native-community/cli
[Internal] - Make the release testing script use the community/cli
Tested locally

[LOCAL][Release-Testing] Update the testing script to use the new template

---

.github/actions/test_ios_helloworld/action.yml
.github/workflows/nightly.yml
.github/workflows/publish-release.yml
.github/workflows/test-all.yml
scripts/e2e/init-template-e2e.js
scripts/utils/monorepo.js

We changed the way we restore the Hermes binary, restoring it from artifacts rather than from cache.
This might have altered a little where the binary is stored and we need to update the path properly
[Internal] - Fix Helloworld ios jobs
GHA are green

[LOCAL][CI] Fix Helloworld ios jobs

---

scripts/e2e/init-template-e2e.js
scripts/release-testing/test-e2e-local.js

These changes updates the testing script so that it follow the approach described [here](https://github.com/facebook/react-native/pull/45144#discussion_r1652489394).
In this way, the testing script:
* Is not bound to a single version of React Native
* Does not require that we publish an `rc.X` version of the template before we release `rc.X` of React Native
[Internal] - Update testing script to work with any version of React Native
Tested locally and verified that the script is packing a template and using the template when initializing the project.

[RN][Testing] Update testing scripts to work with any version of React native

---

packages/react-native/package.json
yarn.lock

We have enabled `consoleManagedByDevToolsDuringStrictMode` flag for OSS builds in https://github.com/facebook/react/pull/29903 for 0.75. This changed behaviour is supported by RDT 5.3.0, which shipped support for dimming console messages from additional invocations during `StrictMode`.
This pull request updates `react-devtools-core` to `^5.3.1`, so this is now supported by default in `0.75`.
[GENERAL][CHANGED] - Added support for dimming logs in console from additional invocations during [StrictMode](https://react.dev/reference/react/StrictMode).

upgrade[react-devtools-core]: ^5.3.1

---

scripts/release-testing/utils/github-actions-utils.js

This change fixes the sorting of the pipelines and it also adds some logging to let users know which workflow it is used for testing.
The url to the workflow that is printed is clickable!
[Internal] - Add logging to local testing script
Tested locally

[LOCAL][RN][Release] Add logging to E2E test script

---

packages/react-native/ReactCommon/react/renderer/components/textinput/CMakeLists.txt

Making `rrc_textinput` allows other libraries (namely `react-native-live-markdown`) to rely on types related to text inputs on Android. Currently, with static linking, type information is duplicated causing `dynamic_casts` to fail.
[ANDROID] [CHANGED] - Change `rrc_textinput` to be a dynamic library
Run RNTester and see that everything works as before

[LOCAL] Make `rrc_textinput` on Android a shared library

---

.circleci/configurations/jobs.yml
.circleci/configurations/top_level.yml
packages/react-native/sdks/hermes-engine/utils/build-ios-framework.sh

We were building Hermes slices without passing the right version, as the mechanism that reads from the podspec got broken somehow.
This fix forces the versions for 0.74.
[General][Fixed] - Pass the right Apple system fvarsions to Hermes
Wait for CircleCI to be green
Download the artifact
Verify that versions are set up correctly.

[RN][Hermes] Fore Hermes versions for slices through env var

---

.circleci/configurations/top_level.yml

The `test_js_prev_lts` is currently red on CCI for 0.75, this fixes it:
https://app.circleci.com/pipelines/github/facebook/react-native/50684/workflows/6c4cff43-77c4-458c-b892-30c796a17850/jobs/1614106
[INTERNAL] - [LOCAL] Bump Node on CircleCI to 18.18 to fix red signal
CI

[LOCAL] Bump Node on CircleCI to 18.18 to fix red signal

---

.github/actions/create-release/action.yml

The create-release tag had an error. it was using the wrong parameter to decide whether to set latest or not.
[Internal] - Use the right parameter in CI to set latest
CI green

[LOCAL][RN][CI] Use the right param to set the 'latest' tag

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/DynamicNative.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/turbomodule/core/TurboModuleInteropUtils.java
packages/react-native/ReactAndroid/src/main/jni/react/jni/JDynamicNative.cpp
packages/react-native/ReactAndroid/src/main/jni/react/jni/JDynamicNative.h
packages/react-native/ReactAndroid/src/main/jni/react/jni/OnLoad.cpp
packages/react-native/ReactCommon/react/nativemodule/core/platform/android/ReactCommon/JavaTurboModule.cpp
packages/react-native/ReactCommon/react/nativemodule/samples/platform/android/SampleLegacyModule.java
packages/rn-tester/js/examples/TurboModule/SampleLegacyModuleExample.js

Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/45944
This diff adds support having (Legacy) Native Modules with functions with parameters of type `Dynamic`. This is currently blocking some libraries making it harder for them to migrate to New Architecture.
I've implemented it by adding a `DynamicNative` implementation of `Dynamic` which holds a reference of the payload as a `folly::dynamic`.
Changelog:
[Android] [Added] - Add support for handling `com.facebook.react.bridge.Dynamic` as parameter type in TurboModules
Reviewed By: mdvacca, cipolleschi
Differential Revision: D60966684
fbshipit-source-id: 2e63bc53ede5277a9c12f1b19f05f6099f5f35f9

[0.75] Add support for handling `com.facebook.react.bridge.Dynamic` as parameter for TurboModules

---

packages/react-native/ReactAndroid/api/ReactAndroid.api
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/imagehelper/ImageSource.kt

Summary:
Fixes https://github.com/facebook/react-native/issues/46077
Changelog:
[Android] [Fixed] - Make Imagesource `open` for inheritance
Differential Revision: D61469357

[0.75] Make Imagesource `open` for inheritance

---

packages/react-native-codegen/package.json

Android fails to build in a pnpm monorepo setup because `yargs` cannot be found:
```
% yarn android
info Installing the app...
> Configure project :app
WARNING: The option setting 'android.jetifier.ignorelist=hermes-android' is experimental.
Signing config for 'release' build type not found; reusing debug config
> Task :react-native-webapis_web-storage:generateCodegenSchemaFromJavaScript FAILED
28 actionable tasks: 6 executed, 22 up-to-date
node:internal/modules/cjs/loader:1148
throw err;
^
Error: Cannot find module 'yargs'
Require stack:
- /~/node_modules/.store/@react-native-codegen-virtual-39ff8dcc54/package/lib/cli/combine/combine-js-to-schema-cli.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
at Module._load (node:internal/modules/cjs/loader:986:27)
at …
```

fix(react-native-codegen): scripts require `yargs`

---

packages/react-native-gradle-plugin/react-native-gradle-plugin/build.gradle.kts
packages/react-native-gradle-plugin/settings-plugin/build.gradle.kts

This removes an unnucessary dependency on `gradle-tooling-api-builders` which is causing a failure on 0.75.
The fix is already landed in main.
Fixes https://github.com/facebook/react-native/issues/32858
[ANDROID] [FIXED] - Fixed build error in Gradle due to missing `serviceOf` import
CI

[0.75] RGNP - Remove unnecessary dependency on `gradle-tooling-api-builders` - serviceOf failure

---

packages/react-native/sdks/hermes-engine/utils/build-ios-framework.sh

// This PR is a cherry-pick to the 0.75 branch
Summary:
Building for the visionOS simulator in the Release scheme requires an x86_64 slice to be included.
[IOS] [FIXED] - Include x86_64 slice when building for visionOS simulator
Pull Request resolved: https://github.com/facebook/react-native/pull/45911
Test Plan: CI Green
Reviewed By: GijsWeterings
Differential Revision: D60828872
Pulled By: cipolleschi
fbshipit-source-id: 74444ac0b6661baf427837d242ba0ca295da0d16

(cherry-pick) fix: Hermes build for visionOS simulator (Release) (#45911)

---

.github/workflows/publish-release.yml

React native 0.75.0, 0.75.1 and 0.75.2 has been published to NPM without the `latest` tag, despite the tag being on the commit.
When debugging why that's happened, I realized that we were not downloading the tags when checking out the repo.
This change fixes that.
[Internal] - Publish React native as latest when the latest tag is specified on git
Next release. We can't run a dry-run test without landing the change first.

[LOCAL][CI] Fetch Github tags in the publish-release job

---

.github/workflows/nightly.yml
.github/workflows/publish-release.yml
.github/workflows/test-all.yml

This change should fix #46213. We are trying to zip the folders generated by the CI and to upload the zip files as artifacts.
The zip should preserve the symlink and Github actions should not manipulate them.
[Internal] - Zip slices on CI to preserve symlinks 
GHA

[RN][CI] Zip slices to preserve symlinks

---

packages/react-native/Libraries/Components/TextInput/RCTTextInputViewConfig.js

The SVC for the `lineBreakModeIOS` is missing. This PR fixes it.
[iOS][Added] - Add the missing `lineBreakModeIOS` prop to iOS SVC for `<Text>`
Tested locally and verified that the warning in React Native DevTools goes away.

[RN][iOS] Fix SVC for lineBreakModeIOS

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/DynamicNative.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/turbomodule/core/TurboModuleInteropUtils.java
packages/react-native/ReactAndroid/src/main/jni/react/jni/JDynamicNative.cpp
packages/react-native/ReactAndroid/src/main/jni/react/jni/JDynamicNative.h
packages/react-native/ReactAndroid/src/main/jni/react/jni/OnLoad.cpp
packages/react-native/ReactCommon/react/nativemodule/core/platform/android/ReactCommon/JavaTurboModule.cpp
packages/react-native/ReactCommon/react/nativemodule/samples/platform/android/SampleLegacyModule.java
packages/rn-tester/js/examples/TurboModule/SampleLegacyModuleExample.js

Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/45944
This diff adds support having (Legacy) Native Modules with functions with parameters of type `Dynamic`. This is currently blocking some libraries making it harder for them to migrate to New Architecture.
I've implemented it by adding a `DynamicNative` implementation of `Dynamic` which holds a reference of the payload as a `folly::dynamic`.
Changelog:
[Android] [Added] - Add support for handling `com.facebook.react.bridge.Dynamic` as parameter type in TurboModules
Reviewed By: mdvacca, cipolleschi
Differential Revision: D60966684
fbshipit-source-id: 2e63bc53ede5277a9c12f1b19f05f6099f5f35f9

[0.74] Add support for handling `com.facebook.react.bridge.Dynamic` as parameter for TurboModules

---

packages/react-native-codegen/package.json
packages/react-native/package.json

`pod install` in a pnpm monorepo setup using latest 0.74 fails due to missing `glob`
```
% pod install --project-directory=ios
Framework build type is static library
[Codegen] Adding script_phases to React-Codegen.
[Codegen] Generating ios/build/generated/ios/React-Codegen.podspec.json
[!] Invalid `Podfile` file: [!] ~/.local/bin/node ios/../node_modules/react-native/scripts/generate-codegen-artifacts.js -p /~/packages/test-app -o /~/packages/test-app/ios -t ios
node:internal/modules/cjs/loader:1148
throw err;
^
Error: Cannot find module 'glob'
Require stack:
- /~/node_modules/.store/react-native-virtual-424e699e97/package/scripts/codegen/generate-artifacts-executor.js
- /~/node_modules/.store/react-native-virtual-424e699e97/package/scripts/generate-codegen-artifacts.js
at …
```

fix(react-native): fix codegen failing in a pnpm monorepo setup

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/flipper/ReactNativeFlipper.kt

This just makes this deprecation warning more severe ahead of the removal of this class in 0.77
[ANDROID] [CHANGED] - Update ReactNativeFlipper deprecation level to ERROR
CI

[0.76] Update ReactNativeFlipper deprecation to ERROR

---

packages/react-native/Libraries/Core/setUpDeveloperTools.js
packages/react-native/Libraries/Utilities/HMRClient.js

With React Native DevTools, we are removing legacy JavaScript log streaming via Metro (https://github.com/facebook/react-native/pull/43558). We had originally taken this step judicially, however to communicate this change better, we will leave this behaviour in place and show a notice for one release cycle.
Annotating as a fix because this impacts the rollout plan for a breaking change.
Learn more about this change in the [Discussion FAQs](https://github.com/react-native-community/discussions-and-proposals/discussions/819).
Changelog:
[General][Changed] - Restore Metro log forwarding, change notice to signal future removal
**Default**
| Before | After |
| - | - |
| <img width="500" src="https://github.com/user-attachments/assets/83248813-c5da-4ca8-b909-f7cb66edc06e"> | <img width="500" …

[0.76][Fix] Restore Metro log forwarding, change notice to signal future removal

---

packages/community-cli-plugin/src/commands/bundle/buildBundle.js

Replicates https://github.com/facebook/react-native/pull/46620 (originally a breaking Metro change + corresponding source code change) for the `0.76-stable` branch.
Signals

[0.76] Fix server.end() usage following Metro bump

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/UIManager.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java
packages/react-native/ReactAndroid/src/test/java/com/facebook/react/RootViewTest.kt
packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedNodeTraversalTest.kt
packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/events/TouchEventDispatchTest.kt
packages/react-native/ReactAndroid/src/test/java/com/facebook/testutils/fakes/FakeUIManager.kt

Summary:
Whe migrating this interface to Kotlin we've subtly introduced a breaking change which is causing a lot of breakages in the ecosystem.
This is forcing users to do:
```
// Before
reactContext.getNativeModule(UIManagerModule::class.java)!!.eventDispatcher
// After
reactContext.getNativeModule(UIManagerModule::class.java)!!.getEventDispatcher()
```
This reverts this breaking change.
Plus the method had a generic parameters which was completely unnecessary so I'm removing it.
Changelog:
[Android] [Fixed] - Undo breaking change on UIManager eventDispatcher accessor
Reviewed By: cipolleschi
Differential Revision: D64533594

[0.76] Undo breaking change on UIManager eventDispatcher accessor

---

packages/react-native/Libraries/Core/setUpErrorHandling.js

This should fix [47215](https://github.com/facebook/react-native/issues/47215). The problem is that we are reworking the error pipeline and this commit made into the stable branch, while the TODO didn't.
This change restore this file to the 0.75 version.
[General][Fixed] - Show early JS errors properly when they happens
Tested in the repro from [47215](https://github.com/facebook/react-native/issues/47215).
| Before | After |
| --- | --- | 
| ![Simulator Screenshot - iPhone 15 Pro - 2024-10-29 at 15 05 31](https://github.com/user-attachments/assets/0fbf5fd6-8236-45d2-b8ed-04f41ba85149) | ![simulator_screenshot_807B3FEB-E2AA-4B7C-807E-E44D459A2042](https://github.com/user-attachments/assets/6280c083-8cc6-4134-aba2-f2eb20b52754) |

[RN][JS] Fix setUpErrorHandling to show early JS errors

---

packages/react-native/Libraries/LogBox/Data/LogBoxData.js
packages/react-native/Libraries/LogBox/__tests__/LogBox-integration-test.js
packages/react-native/Libraries/LogBox/__tests__/LogBox-test.js
packages/react-native/Libraries/LogBox/__tests__/__fixtures__/ReactWarningFixtures.js

Commit to add Logbox changes to 0.76.2:
Changelog: [General][Added] Logbox warning fixes
- **Re-enable integration tests (#46639)**
- **Add integration tests for console errors + ExceptionManager (#46636)**
- **Refactor LogBox tests to spies (#46638)**
- **Fix errors with component stacks reported as warnings (#46637)**
- **[LOCAL] using older version of React Dev Tools**

fix logbox error stack

---

packages/react-native-info/package.json
packages/react-native/cli.js
packages/rn-tester/package.json
yarn.lock

Bumps the CLI to the next version which contains a change for installing Cocoapods with New Architecture by default.
[General][Changed] - Bump `@react-native-community/cli` dependencies to 15.0.1
CI

Bump CLI to 15.0.1

---

packages/react-native-babel-preset/package.json
packages/react-native-babel-preset/src/configs/main.js
yarn.lock

Resolves https://github.com/facebook/hermes/issues/1549.
- Bumps `babel-plugin-syntax-hermes-parser` to `0.15.1` (including new `parseLangTypes` option https://github.com/facebook/hermes/pull/1556).
- Applies `parseLangTypes` in `@react-native/babel-preset`.
Changelog:
[General][Fixed] - When using Babel with plain JavaScript files, support for additional user syntax plugins should be fixed (now uses Babel's parser instead of hermes-parser). There is no change for JS files annotated with `@flow`, where extended JS syntax remains unsupported.
[Meta only] See Phabricator test plan attached to https://github.com/facebook/hermes/pull/1556.
See also hermes-parser changelog — no anticipated incompatibilities from single package bump.

[0.76] Skip hermes-parser under Babel for non-Flow JS code

---

packages/react-native/scripts/codegen/generate-artifacts-executor.js

There is a case where a library is added for a specific platform and unlinked for another platform, because perhaps we would like to use a different library.
The way in which this is implemented is through the `react-native.config.js` file, by setting a specific platform to null.
Currently, Codegen ignore this information and generates the code for all the libraries it can find, including the unlinked ones. This can result in build failures because there are some functions prototype defined with no implementation.
This change takes thos libraries into account and it should fix: #47550.
> [!Note]
> Codegen changed in 0.77, so we don't need to backport this to main
[General][Changed] - Stop generating code for unlinked libraries
Tested in a new app created with 0.76.2, following the repro …

[Codegen] Exclude unlinked libs from codegen

---

.circleci/configurations/jobs.yml
.github/workflows/nightly.yml
.github/workflows/publish-release.yml
.github/workflows/test-all.yml

Do not install CMake on Windows machine
This replicates a fix in 00d5caee992. 0.75 hadn't factored this out into a separate action.
This covers all instances:
```bash
$ git grep 'choco install --no-progress cmake' | wc -l
0
```

[LOCAL] fix/0.75 stable windows cmake

---

packages/react-native/scripts/codegen/generate-artifacts-executor.js

As pointed out by [this comment](https://github.com/facebook/react-native/pull/47712#discussion_r1873766845), the property dependency.platforms might not be defined, as the format
```json
{
"dependencies": {
"dependency-name": {
"root": "path/to/dependency",
}
}
}
```
is also supported.
In this case, we assume that the library is linked to all platforms.
We don't consider the case were `dependency-name.root` is equal to `null`, because that means that the library is not linked to the app at all, and in that case the dependency should be removed by the user.
[General][Fixed] - Improve support for filtering out non supported platforms
Tested on an app with this configuration and it does not crashes.

[RN][Codegen] Better support filtering out non linked platforms

---

.github/actions/maestro-android/action.yml
.github/actions/maestro-ios/action.yml
.github/workflow-scripts/maestro-android.js
.github/workflows/test-all.yml
packages/rn-tester/Podfile.lock

This pr should test Old Arch on template app using maestro
[Internal] - Test old arch in CI with Maestro for template app
GHA

[LOCAL][RN][CI] Add Maestro tests for the Old Arch in Template App

---

.github/actions/build-android/action.yml

While investigating why the configuration
- RNTester Android JSC Debug
Was crashing at startup when testing the release, we found out that the build from source was working fine for rc.0, rc.1, rc.3 and the latest commit on main.
The artifact downloaded from CI, instead, was crashing at startup. 
This signal that the CI APK for RNTester JSC might be corrupted. 
This can be due to same cache restoration, therefore we want to try and clean the android caches to see if this fixes the testing script.
[Internal] - Bump Android build caches to fix the Android APK
Wait for GHA

[LOCAL][Android][0.77] Bump Android Caches

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/StackTraceHelper.java

RNTester JSC Debug is currently insta-crashing on the 0.77 release branch due to:
```
12-31 10:59:36.388 15165 15204 E ReactNativeJS: React Native version mismatch.
12-31 10:59:36.388 15165 15204 E ReactNativeJS:
12-31 10:59:36.388 15165 15204 E ReactNativeJS: JavaScript version: 0.77.0-rc.5
12-31 10:59:36.388 15165 15204 E ReactNativeJS: Native version: 1000.0.0-bb9d7ad9a
12-31 10:59:36.388 15165 15204 E ReactNativeJS:
12-31 10:59:36.388 15165 15204 E ReactNativeJS: Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with `watchman watch-del-all && npx react-native start --reset-cache`.
```
This is causing a `console.error` that is resulting in the crash as one of the frame in the stack doesn't have the line/column number …

[0.77] Fix RN-Tester JSC instacrashing

---

packages/community-cli-plugin/README.md
packages/community-cli-plugin/src/commands/start/index.js
packages/community-cli-plugin/src/commands/start/runServer.js
packages/dev-middleware/src/createDevMiddleware.js
packages/dev-middleware/src/inspector-proxy/Device.js
packages/dev-middleware/src/inspector-proxy/DeviceEventReporter.js
packages/dev-middleware/src/types/EventReporter.js
packages/react-native/Libraries/Core/setUpDeveloperTools.js
packages/react-native/Libraries/Utilities/HMRClient.js
packages/react-native/Libraries/Utilities/HMRClientProdShim.js
packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap

> [!Note]
> This is a separate version of https://github.com/facebook/react-native/pull/49353 / D69469039 targeting the `0.78-stable` branch.
This change adds an opt-in to restore JavaScript log streaming via the Metro dev server, [removed from React Native core in 0.77](https://reactnative.dev/blog/2025/01/21/version-0.77#removal-of-consolelog-streaming-in-metro).
Users can opt into this legacy behaviour by adding the `--client-logs` flag to `npx @react-native-community/cli start`.
- The default experience remains without streamed JS logs.
- The existing "JavaScript logs have moved! ..." notice is printed in all cases, and we do not advertise the new flag for new users.
- Under non-Community CLI dev servers (i.e. Expo), log streaming is restored implicitly.
We will clean up this …

[0.78] Restore Metro log streaming via CLI flag

---

packages/community-cli-plugin/README.md
packages/community-cli-plugin/src/commands/start/index.js
packages/community-cli-plugin/src/commands/start/runServer.js
packages/dev-middleware/src/createDevMiddleware.js
packages/dev-middleware/src/inspector-proxy/Device.js
packages/dev-middleware/src/inspector-proxy/DeviceEventReporter.js
packages/dev-middleware/src/types/EventReporter.js
packages/react-native/Libraries/Core/setUpDeveloperTools.js
packages/react-native/Libraries/Utilities/HMRClient.js
packages/react-native/Libraries/Utilities/HMRClientProdShim.js
packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap

> [!Note]
> This is a separate version of https://github.com/facebook/react-native/pull/49353 / D69469039 targeting the `0.77-stable` branch.
This change adds an opt-in to restore JavaScript log streaming via the Metro dev server, [removed from React Native core in 0.77](https://reactnative.dev/blog/2025/01/21/version-0.77#removal-of-consolelog-streaming-in-metro).
Users can opt into this legacy behaviour by adding the `--client-logs` flag to `npx @react-native-community/cli start`.
- The default experience remains without streamed JS logs.
- The existing "JavaScript logs have moved! ..." notice is printed in all cases, and we do not advertise the new flag for new users.
- Under non-Community CLI dev servers (i.e. Expo), log streaming is restored implicitly.
We will clean up this …

[0.77] Restore Metro log streaming via CLI flag

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/CompositeBackgroundDrawable.kt

This pull request re-applies a previous commit included in React Native versions 0.77 and 0.79, but missing in version 0.78. The commit (55d5c4497621a8dfd6545899754451fcf68dce70) addresses an issue related to elevation radius, which was causing inconsistencies in the rendering behavior. The fix was unable to be cherry-picked directly to 0.78 due to merge conflicts, as discussed by @cortinico in the issue thread [#806](https://github.com/reactwg/react-native-releases/issues/806#issuecomment-2704355102).
[Android] [Fixed] - Elevation prop on android has incorrect border-radius
- I ran tests using the provided rn-tester app and confirmed that the elevation rendering behavior is now consistent across versions.
- The changes were tested on Android, ensuring the elevation radius issue was …

Fix elevation with border-radius set (#48982)

---

packages/react-native/Libraries/Image/Image.android.js
packages/react-native/Libraries/Image/ImageViewNativeComponent.js
packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.kt

Summary:
Fixes https://github.com/facebook/react-native/issues/49075
The Image `defaultSource` prop is causing a runtime error from 0.77 just by using it in the Image component (see error in the linked issue). This might be a regression from some changes in the prop processing logic from either https://github.com/facebook/react-native/issues/47710, https://github.com/facebook/react-native/issues/47713 or https://github.com/facebook/react-native/issues/47754.
[ANDROID] [FIXED] - Fix Image defaultSource runtime error
Pull Request resolved: https://github.com/facebook/react-native/pull/49097
Test Plan:
- Verify it doesn't throw any error on runtime anymore for Android.
- iOS behaviour should not be impacted as changes are Android specific
In the RNTester, you can use the following component: …

[0.77] Fix Android Image `defaultSource` runtime error (#49097)

---

packages/react-native/Libraries/AppDelegate/RCTDefaultReactNativeFactoryDelegate.mm
packages/rn-tester/RNTester/AppDelegate.mm

This change fixes the app startup in the Old Architecture by implementing the `loadSourceForBridge:onProgress:onComplete` method in the `RCTDefaultReactNativeFactoryDelegate` object. 
The method was missing here, so the Bridge was never trying to load the JS bundle from Metro, resulting in an empty app.
[iOS][Fixed] - Implement the  `loadSourceForBridge:onProgress:onComplete` in the `RCTDefaultReactNativeFactoryDelegate`.
Tested locally in RNTester by removing the method in the AppDelegate (the app was loading blank) and then moving it into the `RCTDefaultReactNativeFactoryDelegate` (the app was loading again).
I also tested it in a new RN App from the template, built starting from 0.79.0-rc.0

[LOCAL][RN][iOS][OldArch] Add missing loadFromSource method in the DefaultRNFactoryDelegate

---

packages/community-cli-plugin/package.json
packages/community-cli-plugin/src/commands/start/middleware.js
packages/react-native/react-native.config.js

Picks: https://github.com/facebook/react-native/pull/49518
[GENERAL][FIXED] Fix registering of `start` and `bundle` commands with community CLI and isolated node_modules.
As in main - eg testing with RN 0.79-rc.2:

[0.77] community-cli-plugin: resolve cli-server-api via peer dependency on cli

---

packages/community-cli-plugin/package.json
packages/community-cli-plugin/src/commands/start/middleware.js
packages/react-native/react-native.config.js

Picks: https://github.com/facebook/react-native/pull/49518
[GENERAL][FIXED] Fix registering of `start` and `bundle` commands with community CLI and isolated node_modules.
As in main

[0.78] community-cli-plugin: resolve cli-server-api via peer dependency on cli

---

.github/workflow-scripts/publishTemplate.js

GHA passes the version to the script using the tag, therefore, the version we receive is something like `v0.X.Y`.
The script, instead, expect the version to be `0.X.Y`, with no leading `v`.
This change fixes the script removing the `v` if present. It also mimic a fix we already have on main.
An example of a failing job is [here](https://github.com/facebook/react-native/actions/runs/13944332034/job/39031068356)
[Internal] - Fix release script by dropping the passed `v`.
Next release.

[RN][CI][Releases] Remove the v prefix from the version passed by GHA to the script

---

.github/actions/maestro-android/action.yml

Android E2E maestro tests are failing on 0.76-stable because `actions/upload-artifact` v3 has been deprecated.
https://github.com/facebook/react-native/actions/runs/14044976491/job/39325684374
[INTERNAL] [FIXED] - Bump `actions/upload-artifact` version on Android E2E maestro tests
Android E2E maestro tests should be green

[0.76][github] Fix upload-artifact version on maestro android

---

.github/actions/build-hermesc-windows/action.yml

Windows executor has been updated by github and they now ship with CMake 4.0. (https://github.com/actions/runner-images/issues/11926)
This is not compatible with building HermesC on windows machines. This change attempts to downgrade cmake to 3.31.6, the same version we used to use before.
[Internal] - downgrage Cmake to 3.31.6
GHA

[CI][Windows] Downgrade CMake to 3.31.6

---

packages/react-native/scripts/codegen/generate-artifacts-executor.js

We realized that when calling
npx react-native-community/cli codegen --path . --platform all --outputPath /tmp/codegen
We were generating in the android folder some files that are Apple-specific.
With this change, we should stop generating the Apple specific files in Android.
[General][Fixed] - Do not generate Apple specific files for Android
| Before | After |
| ------ | ------|
|  <img width="441" alt="Screenshot_2025-04-11_at_13 30 09" src="https://github.com/user-attachments/assets/cfa873b3-bc84-414c-8308-972a1169dff9" /> |  <img width="471" alt="Screenshot 2025-04-11 at 13 44 16" src="https://github.com/user-attachments/assets/7a398b61-8faf-4810-a830-802be560a4d5" /> |

[RN][Codegen] Do not generate Apple specific file for Android

---

packages/react-native/scripts/codegen/generate-artifacts-executor.js

While we were refactoring the generation of the podspec, we made a mistake and we started generating the `ReactCodegen.podspec` for both libraries and apps.
This must be generated only for apps.
[iOS][Fixed] - Generate ReactCodegen.podspec only for apps.
GHA

[RN][iOS] Do not generate ReactCodegen.podspec for libraries

---

packages/react-native/Libraries/AppDelegate/RCTReactNativeFactory.mm
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlags.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxAccessor.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxInterop.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsDefaults.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsLocalAccessor.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsOverrides_RNOSS_Stable_Android.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsProvider.kt
packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.cpp
packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.cpp
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.cpp
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDefaults.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDynamicProvider.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsProvider.h
packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.cpp
packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.h
packages/react-native/ReactCommon/react/renderer/core/ShadowNode.cpp
packages/react-native/ReactCommon/react/renderer/core/ShadowNode.h
packages/react-native/ReactCommon/react/renderer/mounting/updateMountedFlag.cpp
packages/react-native/scripts/featureflags/ReactNativeFeatureFlags.config.js
packages/react-native/src/private/featureflags/ReactNativeFeatureFlags.js
packages/react-native/src/private/featureflags/specs/NativeReactNativeFeatureFlags.js

Backporting the useShadowNodeStateOnClone and updateRuntimeShadowNodeReferencesOnCommit features to 0.79 and enabling both features by default.
[Internal] - Enable useShadowNodeStateOnClone and updateRuntimeShadowNodeReferencesOnCommit for OSS
```
yarn test
```
```
Test Suites: 234 passed, 234 total
Tests:       2 skipped, 5139 passed, 5141 total
Snapshots:   1745 passed, 1745 total
Time:        45.256 s
Ran all test suites.
✨  Done in 49.48s.
```

Backporting to 0.79 and enabling the features fixing issue #49694

---

3077396185.mdt
packages/react-native/scripts/codegen/__tests__/__snapshots__/generate-artifacts-executor-test.js.snap
scripts/releases/__tests__/__snapshots__/set-rn-artifacts-version-test.js.snap
scripts/releases/__tests__/__snapshots__/set-version-test.js.snap
scripts/releases/__tests__/set-rn-artifacts-version-test.js
scripts/releases/set-rn-artifacts-version.js

test-js jobs are failing because the codegen snapshot tests generates a Podspecs withan hardcoded version that does not matches the version we are about to release.
This fix updates the script that set the RN version to make sure it also updates the Codegen snapshots.
This change also fixes the currently broken snapshots.
[Internal] - Fix set-rn-version script to update codegen snapshots
Tested locally by
```
node scripts/release/set-rn-version --built-type release --to-version 0.80.0-rc.0
```
And verifying that only the snapshot got updated.
Tested that the jest test were passing by running
```
yarn test generate-artifacts-executor-test
```

[RN][Release] Fix set-rn-version to account for codegen snapshot test files

---

packages/react-native/ReactAndroid/api/ReactAndroid.api
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.kt

I am picking https://github.com/facebook/react-native/commit/d07b2a9d992c7240006d7d3607a109215deff5c6 into 0.80. There are several merge conflicts so doing this as a PR per @cortinico's recommendation in https://github.com/reactwg/react-native-releases/issues/952. 
This change addresses this issue: https://github.com/facebook/react-native/issues/51072
A change I made in 0.79 broke some blurring behavior on older Android versions. 
Fix commit: facebook/react-native@d07b2a9 
[Android] [Fixed] - Fix broken focus behavior for TextInput in older Android versions (< 9)

[0.80] Fix broken focus behavior for TextInput in older Android versions (< 9)

---

packages/react-native/React/CoreModules/RCTDeviceInfo.mm

This fixes the bug where Dimensions (Height and width) are not changing when the orientation changes. Me and  @anultravioletaurora also experienced this while working on [Jellify](https://github.com/Jellify-Music/App). PR:- https://github.com/Jellify-Music/App/pull/416 
Also fixes https://github.com/facebook/react-native/issues/50861
The bug is already fixed on main and 0.80 . This PR is only for 0.79-stable.
[IOS][FIXED]Dimensions not changing with orientation changes

Fix Dimensions not changing when orientation changes

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlags.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxAccessor.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxInterop.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsDefaults.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsLocalAccessor.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsProvider.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.cpp
packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.cpp
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.cpp
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDefaults.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDynamicProvider.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsProvider.h
packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.cpp
packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.h
packages/react-native/scripts/featureflags/ReactNativeFeatureFlags.config.js
packages/react-native/src/private/featureflags/ReactNativeFeatureFlags.js
packages/react-native/src/private/featureflags/specs/NativeReactNativeFeatureFlags.js

I am picking https://github.com/facebook/react-native/commit/d07b2a9d992c7240006d7d3607a109215deff5c6 into 0.79. There are several merge conflicts so doing this as a PR per @cortinico's recommendation in https://github.com/reactwg/react-native-releases/issues/952. The main issue being that ReactEditText is Java in this branch as opposed to Kotlin.
This change addresses this issue: https://github.com/facebook/react-native/issues/51072
A change I made in 0.79 broke some blurring behavior on older Android versions.
Fix commit: https://github.com/facebook/react-native/commit/d07b2a9
Changelog:
[Android] [Fixed] - Fix broken focus behavior for TextInput in older Android versions (< 9)
https://github.com/user-attachments/assets/6ca1d323-2630-4804-b339-0b1fcb35c3c5 …

[0.79] Fix broken focus behavior for TextInput in older Android versions (< 9)

---

packages/react-native/scripts/codegen/__tests__/generate-artifacts-executor-test.js
packages/react-native/scripts/codegen/generate-artifacts-executor.js

Backport of #51838 to 0.79
[IOS] [FIXED] - Skip codegen for selectively disabled libraries in react-native.config.js
1. Install a library that has the componentProvider field set in the codegen config (for example: react-native-safe-area-context and react-native-screens or see [reproducer](https://github.com/aattola/rn-codegen-exclude?rgh-link-date=2025-06-05T12%3A13%3A05Z))
1. Exclude library with react-native.config.js
1. install pods / run codegen
1. Check that codegen actually excluded the specified dependencies from: ios/build/generated/ios/RCTThirdPartyComponentsProvider.mm

[RN][Codegen] Backports fix: exclusion of selectively disabled libraries from codegen generation

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java

Based on the proposed fix https://github.com/facebook/react-native/pull/52333, it seems the cause of the regression #50274 was likely #46896.
Since #50274 is a more significant bug than the one fixed by #46896, and both only affect legacy architecture [which is frozen](https://github.com/reactwg/react-native-new-architecture/discussions/290), we're going to roll back to the least-worst state.
[ANDROID] [FIXED] - Fix Legacy Arch reload failures #50274
TBC in 0.77.3 release testing

[LOCAL][0.77] Revert #46896 - Attempt to fix #50274

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/statusbar/StatusBarModule.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/DisplayMetricsHolder.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/modal/ReactModalHostView.kt
packages/react-native/ReactCommon/React-FabricComponents.podspec
packages/react-native/ReactCommon/react/renderer/components/modal/CMakeLists.txt
packages/react-native/ReactCommon/react/renderer/components/modal/ModalHostViewComponentDescriptor.h
packages/react-native/ReactCommon/react/renderer/components/modal/ModalHostViewState.h
packages/react-native/ReactCommon/react/renderer/components/modal/ModalHostViewUtils.h
packages/react-native/ReactCommon/react/renderer/components/modal/platform/android/JReactModalHostView.h
packages/react-native/ReactCommon/react/renderer/components/modal/platform/android/ModalHostViewUtils.cpp
packages/react-native/ReactCommon/react/renderer/components/modal/platform/cxx/ModalHostViewUtils.cpp

Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/51048
Fixes https://github.com/facebook/react-native/issues/50442 Closes https://github.com/facebook/react-native/pull/50704
Users reported that Modals on Android are first renderer anchored in 0,0. That results in them being on the top left corner of the screen for some seconds.
This is happening because the native state of the Modal on Android as width/height set at 0,0 - which we then update in a subsequent callback.
I'm fixing this by making sure we render the Modal the first time with the right screen size - the status bar size
Changelog:
[Android] [Fixed] - Fix Modal first frame being rendered on top-left corner
Reviewed By: javache
Differential Revision: D73948178
fbshipit-source-id: …

[LOCAL][0.77] Fix Modal first frame being rendered on top-left corner (#51048)

---

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlags.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxAccessor.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsCxxInterop.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsDefaults.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsLocalAccessor.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsOverrides_RNOSS_Experimental_Android.kt
packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/featureflags/ReactNativeFeatureFlagsProvider.kt
packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.cpp
packages/react-native/ReactAndroid/src/main/jni/react/featureflags/JReactNativeFeatureFlagsCxxInterop.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.cpp
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlags.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.cpp
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsAccessor.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDefaults.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsDynamicProvider.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsOverridesOSSExperimental.h
packages/react-native/ReactCommon/react/featureflags/ReactNativeFeatureFlagsProvider.h
packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.cpp
packages/react-native/ReactCommon/react/nativemodule/featureflags/NativeReactNativeFeatureFlags.h
packages/react-native/ReactCommon/react/renderer/mounting/ShadowTree.cpp
packages/react-native/ReactCommon/react/renderer/mounting/ShadowTree.h
packages/react-native/scripts/featureflags/ReactNativeFeatureFlags.config.js
packages/react-native/src/private/featureflags/ReactNativeFeatureFlags.js
packages/react-native/src/private/featureflags/specs/NativeReactNativeFeatureFlags.js

This is a collection of picks for the 0.81 branch only:
- https://github.com/facebook/react-native/commit/21cd09d4c0fc7622ecf0247d4c4f1251dc06c154
- https://github.com/facebook/react-native/commit/25c61123fb246b3791df52f7be1baab420e3e54c
- https://github.com/facebook/react-native/commit/391a6b87a0df490207dacd1b08ee7f5b82a8bc68
[INTERNAL] - Implement mechanism to prevent ShadowTree commit exhaustion
CI

[0.81] Implement mechanism to prevent ShadowTree commit exhaustion

---

.github/workflows/prebuild-ios-core.yml
packages/react-native/Libraries/PushNotificationIOS/React-RCTPushNotification.podspec
packages/react-native/scripts/ios-prebuild/setup.js
packages/react-native/scripts/ios-prebuild/xcframework.js

This change reverts D78158734 which was a patch to make the dynamic frameworks work properly because we were not exporting the FBReactNativeSpec headers in prebuilds correctly.
This change fixes this, by exposritng those headers correctly.
This is a port of https://github.com/facebook/react-native/commit/c71c68121a16c8c040b1794612d2b0cc490a4e8f to RN 0.81
[Internal] -
The commit has landed in main already

[RN][iOS]Fix FBReactNativeSpec headers in prebuilds for 0.81

---

packages/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt
packages/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt
packages/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/AgpConfiguratorUtils.kt
packages/react-native/ReactAndroid/build.gradle.kts
packages/react-native/ReactAndroid/hermes-engine/build.gradle.kts
packages/react-native/ReactAndroid/src/main/jni/react/hermes/reactexecutor/CMakeLists.txt
packages/react-native/ReactAndroid/src/main/jni/react/runtime/hermes/jni/CMakeLists.txt
packages/react-native/ReactAndroid/src/main/jni/react/runtime/jni/CMakeLists.txt
packages/react-native/ReactCommon/hermes/executor/CMakeLists.txt
packages/react-native/ReactCommon/hermes/inspector-modern/CMakeLists.txt
packages/react-native/ReactCommon/jsinspector-modern/CMakeLists.txt
packages/react-native/ReactCommon/react/debug/CMakeLists.txt
packages/react-native/ReactCommon/react/runtime/CMakeLists.txt
packages/react-native/ReactCommon/react/runtime/hermes/CMakeLists.txt
packages/rn-tester/android/app/src/debug/AndroidManifest.xml
packages/rn-tester/android/app/src/main/AndroidManifest.xml

This backports #52620 to the `0.81-stable` branch.
This creates a `debugOptimized` build type for React Native Android, meaning that we can run C++ optimization on the debug build, while still having the debugger enabled. This is aimed at improving the developer experience for folks developing on low-end devices or emulators.
Users that intend to debug can still use the `debug` variant where the full debug symbols are shipped.
[ANDROID] [ADDED] - Create a debugOptimized buildType for Android
Test Plan:
Tested locally with RNTester by doing:
```
./gradlew installDebugOptimized
```

[0.81] Backport: Create a `debugOptimized` buildType for Android
