facebook/react-native

docs/Tutorial.md

I feel this is what the author meant :)

Fix a couple typos

---

packager/packager.js

[react-packager] Fix assetRoots when starting in node_modules,

---

.travis.yml
website/setup.sh

Had to change around the config since this is now a public repo so we
can't use SSH auth. This seems to work though.

Autobuild website on Travis

---

docs/Tutorial.md

Fixed typo in tutorial

---

docs/Network.md

**docs/Networking.md**
- adjust the plurality of goal to goals

Adjust the plurality of goal to goals in docs/Networking.md

---

docs/EmbeddedApp.md

Use correct capitalisation in CocoaPods

---

README.md

Removed an extra bracket and line end "];" in the callback of the processString method.

Minor update README.md - 'Extensibility' Section for iOS code (callback)

---

README.md

Please correct me if I am wrong as I don't know ObjC too well yet (still learning).

fix objc syntax error

---

docs/Troubleshooting.md

Added quick reinstall --HEAD fix for watchman
https://github.com/facebook/watchman/issues/90

Add watchman permission errors

---

docs/LinkingLibraries.md

Reverts facebook/react-native#561

Revert "Fixed broken image for AddToBuildPhases.png"

---

docs/LinkingLibraries.md

Reverts facebook/react-native#562

Revert "Fixed image link for AddToSearchPaths.png"

---

docs/NativeModulesIOS.md

#import "RCTBridgeModule.h"  for   RCT_EXPORT();
#import "RCTLog.h" for RCTLogInfo(...)

missing #import "RCTLog.h"

---

.travis.yml

Build the website without publishing on PRs

---

docs/Troubleshooting.md

-corrected typo in troubleshooting.md- changed 'Wathcman' to 'Watchman'
-changed tense to make make more readable- 'to load' to 'from loading'

(update) Typo in Watchman

---

docs/NativeModulesIOS.md

Made small changes to the wording under  **NOTE**: About array and map

Fix wording in NativeModulesIOS.md

---

website/layout/AutodocsLayout.js

This would have prevented #709.

Fail docs build on missing component file

---

README.md

change to git clone https://github.com/facebook/react-native.git

---

docs/RunningOnDevice.md

Minor change: fixes the sentence to use `whether` instead of `whenever`

[docs] Change 'whenever' to 'whether'

---

packager/packager.sh
scripts/e2e-test.sh

This should help us debug e2e test failures

Print server logs from e2e tests

---

scripts/e2e-test.sh

Sometimes it timeout in e2e tests, going to check logs

Debugging watchman

---

Examples/UIExplorer/ActivityIndicatorIOSExample.js
Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js
Libraries/ReactIOS/ReactIOSMount.js

Flow v0.10.0 complains about 3 things that v0.9.2 doesn't. This fixes those errors.

Clean the errors that Flow v0.10.0 finds

---

docs/NativeModulesIOS.md

This adds documentation to briefly explain how to export a Swift module.

Documentation for exporting Swift Native Modules

---

docs/NativeComponentsIOS.md

Fixed some syntax errors and tidied up the sample code.

Fix some typos in NativeComponentsIOS.md

---

.travis.yml

Green tests are better than red tests

Disable watchman on Travis

---

Libraries/Components/ScrollView/ScrollView.js

Simple one character change - add a missing space

Fix scrollview doc type - canimprove -> can improve

---

website/core/HeaderLinks.js

```
$ curl -I  http://github.com/facebook/react-native
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://github.com/facebook/react-native
Connection: close
```
This saves some network time.

Update website header link github url: use HTTPS

---

docs/LinkingLibraries.md

Fix typo in LinkingLibraries.md

---

website/layout/AutodocsLayout.js

Fix issue #1223

---

docs/EmbeddedApp.md

-change one sentence to improve grammar

Fix grammar in EmbeddedApp.md

---

local-cli/cli.js

Warn if `init` is called from existing project

---

.gitignore

Add additional rule to exclude files like `npm-debug.log`.

Update .gitignore with *.log

---

react-native-cli/index.js
react-native-cli/package.json

ask confirmation on init command

---

CONTRIBUTING.md

Removed the quotes from CLA acronym to adhere to MLA style guide
"CLA" => CLA

Fixed grammar in CLA section of contribution guide

---

local-cli/bundle.js

Needed this to bundle my non-standard react-native app.

[CLI][Bundle][Packager] Implement --root --assetRoot and --out for consistency with packager and more flexibility

---

website/src/react-native/index.js

getInitialState and componentDidMount were nested inside the render method.

Fix incorrect code sample

---

packager/transformer.js

Enable react.displayName transform

---

docs/Image.md

a similar commit: aa7e318a3f2144eda134420da74cf486a1540d32

[Docs] Xcode has a lower-case c

---

docs/Timers.md

Adds install instructions for `react-timer-mixin` to the `TimerMixin` docs. /cc @brentvatne

[Docs] Update TimerMixin docs.

---

docs/EmbeddedApp.md

1. 'Install' should be 'installed' (past tense)
2. Change 'checkout' to 'check out' (check out is to inspect and checkout refers to "checking out at a hotel/grocery store")

Minor grammatical fixes:

---

Libraries/ReactIOS/renderApplication.ios.js

Hotfix fri 10 july

---

local-cli/bundle.js

We need this command line to integration with other system. Currently 'URL_PATH' is hard code in line. Make this variable to configurable.

add cli bundle url params

---

local-cli/generator/templates/_flowconfig
scripts/e2e-sinopia.config.yml
scripts/e2e-test.sh

* use new _flowconfig in generator template
* increase sinopia max_body_size
* remove breaking `cd` command from e2e-test.sh

[e2e] fix e2e tests

---

react-native-cli/CONTRIBUTING.md

[cli] add docs on how to contribute to the CLI

---

website/core/HeaderLinks.js
website/src/react-native/css/react-native.css
website/src/react-native/showcase.js

Initial implementation of showcase. Everyone should PR to add a new showcase div. Happy to add my app if you guys approve.
Sample screenshot attached below.
fixes #2184.
cc @brentvatne @vjeux

showcase link on React-native website.

---

website/src/react-native/css/react-native.css

updated the showcase item sizes.
cc @vjeux

[Showcase] Reduce the width on showcase items

---

website/src/react-native/showcase.js

Add DropBot app to Showcase

---

website/src/react-native/showcase.js

Added Leanpub's iOS app to the list of showcase apps.  It's the reader / library for the website https://leanpub.com

Add leanpub to the list of showcase apps.

---

website/src/react-native/showcase.js

New app developed in RN just went live in the German app store.

Showcase: New app "Yoloci"

---

website/src/react-native/showcase.js

Text/voice communication app for gamers developed in React Native.

Showcase: New app "Discord"

---

website/src/react-native/showcase.js

App for lottery buyers in Singapore to get the latest lottery results

Showcase: New app "SG Toto 4d"

---

README.md

This new README talks more about the react-native project, repository, and contribution process (the old one was more focused on technical details). @brentvatne and I want people to get help and file issues & PRs more effectively. Here's a first draft that we believe helps with that.

[README] New README co-authored with @brentvatne

---

docs/GettingStarted.md

[Docs] xcodeproj for new projects is now in iOS/

---

docs/Testing.md

With the added information a react-native developer will be able to run jest tests without errors. First time contributing to react-native so please let me know if I missed something :)
As it is I was running into issues running jest tests. The configuration added was added from the react-native package.json.

Update Testing.md with pre-processing information

---

website/server/extractDocs.js

Thanks to @fkling for the fix.

Add back Transform/Flexbox links to style documentation

---

local-cli/generator-ios/templates/xcodeproj/project.pbxproj

Disable code stripping for DEBUG builds

---

local-cli/generator/templates/_flowconfig

Updated from https://github.com/facebook/react-native/blob/master/Examples/SampleApp/_flowconfig

Update generator's flow config

---

.gitignore

Reverts facebook/react-native#2733

Revert "ignore npm-debug.log"

---

docs/Debugging.md

fixed one typo

---

README.md

Raise some awareness of the tag and let people know they can help by answering qquestions and be altruistic and helpful.

[README] Add link to react-native tag on Stack Overflow

---

docs/Tutorial.md

Updated path since Xcode project is now under `ios` directory.

Update iOS .xcodeproj path

---

ReactAndroid/README.md

Right now, as the NDK is required, let's guide people to the download & extraction page.

[Docs][Android] Adds NDK download instructions

---

react-native-cli/index.js

[cli] don't swallow require(local_cli) errors

---

website/src/react-native/showcase.js

Ziliun.com article reader app built with React Native. 
github: https://github.com/sonnylazuardi/ziliun-react-native
play store: https://play.google.com/store/apps/details?id=com.ziliunapp

Showcase: New app "Ziliun"

---

local-cli/generator/templates/_flowconfig

Bump flow version

---

local-cli/bundle.js

As requested by @vjeux, this moves the change to this file to a separate PR.
For more info see #2905.

Update cacheVersion in bundle.js

---

.travis.yml
local-cli/__tests__/generator-android-test.js
local-cli/__tests__/generator-ios-test.js

Will kick travis a bunch of times to see if the flakiness is gone and merge if it worked.

[cli] use different names in generator tests

---

docs/NativeModulesAndroid.md

changed
`To make it simpler for to access your new functionality ...`
to
`To make it simpler to access your new functionality ...`

Fix Grammar

---

local-cli/run-android.js
local-cli/run-packager.js

Also use ANDROID_HOME env var when running adb.

[cli] spawn xterm on linux to run the packager

---

docs/KnownIssues.md
docs/Performance.md

Thanks @ide for proofreading for me :heart_eyes:
cc @mkonicek @vjeux @nicklockwood

[Docs] First pass at performance guide

---

local-cli/init.js

[cli] make init backwards-compatible

---

local-cli/bundle.js

Add --write-sourcemap option to 'bundle' cli command (fixes #3202)

---

website/src/react-native/showcase.js

This conference app we just released was built with react-native, so thought it might be good to add it to the showcase.

Adding AIGA Design Conference app to showcase

---

website/src/react-native/showcase.js

Updated the "by whom" info.
Test Plan: Build and view website.

[Showcase] Update attribution for Exponent

---

docs/KnownIssues.md

Line 53: "currenty" => "currently"
Thanks to everyone on the team for such a fantastic tool!
Already signed CLA.

[Docs] fix typo in KnownIssues.md

---

website/server/extractDocs.js

Not as descriptive as it could be but that can be work for a separate PR

[Docs] Add Dimensions to API docs

---

docs/JavaScriptEnvironment.md

Re-sync the documentation wrt actual transformations applied in:
https://github.com/facebook/react-native/blob/master/packager/transformer.js#L35-L48

Update list of babel transformations in JavascriptEnvironment doc

---

docs/RunningOnDeviceAndroid.md

You can access the rage menu via adb by sending the keycode manually if you don't have a physical device that you can shake.

Document opening rage menu via adb

---

website/src/react-native/showcase.js

Happy react-native users over here :)

add RepairShopr to showcase

---

ReactAndroid/README.md

Updated android SDK requirements on the READ.me to the SDK 23.

updated ReactiveAndroid installation info

---

website/server/generate.js

…ite them without trying to process them

Documentation: Fix the site generator so the simulator's supporting javascript files get written

---

.travis.yml

$APPETIZE_TOKEN is now available

Add appetize.io token to travis environment

---

website/layout/AutodocsLayout.js
website/src/react-native/css/react-native.css
website/src/react-native/js/scripts.js

- Hover effect for simulator image
- "Run this example" is now a link and opens the modal
- Added Appetize.io link in the modal
- Adjusted simulator iframe size

Documentation: Adjust styling and add Appetize link in the modal

---

docs/EmbeddedAppIOS.md

This is to resolve https://github.com/facebook/react-native/issues/3440

Update documentation with improved Cocoapods workflow

---

docs/NativeModulesAndroid.md

PR because of issue #3475.
https://github.com/facebook/react-native/issues/3475
Update documentation for native module (Android).

Clarified ReactInstanceManager paragraph.

---

website/src/react-native/showcase.js

Foodstand is a community built around eating good food. We've rewritten our iOS app in React Native and are would love to submit it to the showcase!
Thanks!

Add Foodstand to RN showcase

---

docs/Videos.md

Add "React Native: Under the Hood" to videos

---

website/src/react-native/showcase.js

Adding CANDDI's app to the showcase.

CANDDi's iOS app

---

website/src/react-native/showcase.js

This app was built using React Native and was created to provide a more optimized mobile experience for reading news articles. I would love to have it added to the showcase!

Add Okanagan News App to showcase

---

docs/Animations.md

Line 461: "simlar" => "similar"
Line 545: "tighly" => "tightly"
CLA signed. Thanks for the superb work!

[docs] fix typos (docs/Animations)

---

scripts/objc-test.sh

Just pushed this internally, let's also use the latest simulator version when testing on Travis

Use latest simulator version

---

website/src/react-native/showcase.js

Go Fire APP All use react native Development

add Go Fire APP to showcase

---

docs/NativeModulesIOS.md

Fixes https://github.com/facebook/react-native/issues/3644
I am done with CLA. Please let me know if anything needs to be changed.

add missing curly brace in NativeModulesIOS.md

---

website/src/react-native/showcase.js

thanks for the useful showcase

add makerist app

---

website/src/react-native/showcase.js

CLA signed. The app is completely react-native.

Add RenovationFind App to the showcase

---

react-native-cli/README.md

@mkonicek, @foghina do you mind taking a look? :)

Steps for alternative testing workflow of the cli

---

website/src/react-native/showcase.js

https://play.google.com/store/apps/details?id=io.scrollback.neighborhoods

Add Hey Neighbor to showcase

---

website/src/react-native/showcase.js

I just published my app done by react native in both Play Store and App Store.
Can you help to list my app on the react native website ? Thanks!!
https://play.google.com/store/apps/details?id=com.bitstrek.maxreward&hl=en
https://itunes.apple.com/us/app/maxreward/id1050479192?ls=1&mt=8

Include my app done by React Native

---

website/src/react-native/showcase.js

I've added the Harmonizome application to the showcase. It is also available for Android, however, I'll wait until we can add multiple links to one app before I include it.

Added Harmonizome

---

docs/Images.md

Update Images.md(remove the unexisted "screenshot")

---

docs/DevelopmentSetupAndroid.md

I struggled figuring this out - it took me an inordinate amount of googling to find a stackoverflow post that told me how to bring up the developer menu. 
My hope is that this will help others like me, who are keen to check out cross platform RN.

Instructions to bring up the developer menu

---

react-native-cli/package.json

Add license and source info

---

docs/Animations.md

remove precomputeStyle

---

website/src/react-native/showcase.js

yay, first react-native app is done.

added WOOP App

---

docs/EmbeddedAppIOS.md
docs/GettingStarted.md

npm 3 is really slow compared to npm 2, to the extent that people are reporting bugs.

[Docs] Suggest installing npm 2 instead of npm 3 for perf reasons

---

website/src/react-native/showcase.js

Added our app made in React native to the show case.

Added Townske to showcase

---

docs/Performance.md

Update removeClippedSubviews default value

Update removeClippedSubviews default value

---

docs/CommunicationIOS.md
docs/EmbeddedAppIOS.md

WARNING: I was not able to run the website locally because of a bug, so please test it before merging.
I'll appreciate any kind of feedback!

[docs] A guide covering communication between native and RN on IOS.

---

website/src/react-native/showcase.js

Reverts facebook/react-native#4439
Sorry for the trouble.

Revert "Add TYDY to the Showcase" (Taking TYDY off)

---

docs/AndroidBuildingFromSource.md
docs/AndroidUIPerformance.md

Mostly taken from @chirag04 's comment here - https://github.com/facebook/react-native/issues/3337#issuecomment-147243916
cc @ide @mkonicek

[Android] Add docs on building from source

---

docs/AndroidBuildingFromSource.md

Improve docs for Building from source

---

docs/CommunicationIOS.md

Very minor typo. 
First contribution - CLA submitted.

[Docs] fixes minor typo by adding space

---

docs/Network.md

@ide I think we want to add `await` and promises to `frisbee` before doing this?

Switched recommendation from superagent to frisbee

---

docs/EmbeddedAppIOS.md

Fix with correct init call on RCTRootView due to change in method signature from commit 261f9434e54274a68d2cb50644c436197ef48baa

Fix EmbeddedAppIOS documentation

---

docs/LinuxWindowsSupport.md

update the way of starting packager on windows

update the way of starting packager on windows

---

website/src/react-native/showcase.js

Add 'Eat or Not' - https://itunes.apple.com/us/app/eat-or-not/id1054565697?mt=8 to showcase

Add 'Eat or Not' to showcase

---

docs/DirectManipulation.md

Since there are no precomputeStyle module now.

remove Precomputing Style

---

docs/NativeModulesIOS.md

[#4734](https://github.com/facebook/react-native/issues/4734)

fixed documentation error for native modules docs page

---

docs/Accessibility.md
docs/Tutorial.md

Fixes few small typos in `./docs` folder.

Bugfix - Typos in ./docs

---

website/src/react-native/showcase.js

showcase Lugg's android app

---

docs/Videos.md

Added Brent Vatne's "From React web to native mobile: mapping out the unknown unknowns | Brent Vatne | Reactive 2015"  and Martin Konicek's "Under The Hood of React Native | Martin Konicek | Reactive 2015"

[Doc][Minor] embed more videos

---

website/src/react-native/showcase.js

I've added our newly released, React Native based application 'Pimmr' to the showcase page.

Add 'Pimmr' to Showcase page

---

website/src/react-native/showcase.js

WEARVR IOS App added to the showcase js.

added WEARVR app to showcase

---

website/src/react-native/css/react-native.css

Issue # [4777](https://github.com/facebook/react-native/issues/4777)

fixed showcase to display well on mobile

---

website/src/react-native/showcase.js

Added android link to WEARVR in showcase

added WEARVR android version to showcase

---

website/src/react-native/showcase.js

Added 'Koza Gujarati Dictionary' to showcase

Add 'Koza Gujarati Dictionary' to showcase

---

website/src/react-native/showcase.js

Adding CBS Sports Franchise Football to the React Native showcase,

Added CBS Sports Franchise Football to Showcase

---

CONTRIBUTING.md

See this comment of PR #4866: https://github.com/facebook/react-native/pull/4866#issuecomment-166612075
/cc @bestander

Add mention of the license comment in CONTRIBUTING.md

---

react-native-cli/index.js

add react-native version output for -v/--version

---

website/README.md
website/setup.sh

- always start website/setup.sh in website
- use setup.sh in website README

Docs for website setup

---

docs/DirectManipulation.md

Reverts facebook/react-native#4059

Revert "remove Precomputing Style"

---

README.md

added easy tasks to README for new contributors

---

.travis.yml

Updates the Travis CI environment to install Node 5.

[Node 5] Run Travis CI tests with Node 5 and npm 3

---

docs/NativeComponentsIOS.md

The target line seems changed much over time and has no explicit relation with "mappings".

remove broken link

---

.travis.yml
scripts/e2e-test.sh
scripts/objc-test.sh

Move tests to Xcode 7.2

---

docs/GettingStarted.md

Spent an hour trying to find this doc. Hope this helps the next person!

Link to iOS device docs

---

docs/Images.md

It can be overridden with undefined to scale dynamically

Add details about undoing require() image sizing

---

website/src/react-native/showcase.js

[Website] Add MoneyLion App

---

docs/Animations.md

[Doc][Animation guide][Minor]fix comment by shifting to seperate line

---

ReactAndroid/src/main/java/com/facebook/react/modules/clipboard/ClipboardModule.java

Reverts facebook/react-native#5368

Revert "Remove unused ApplicationContext fetch"

---

website/src/react-native/showcase.js

Add utayomin to showcase. This is a Tanka(Japanese poem) application. There are many beautiful Japanese characters.

Add utayomin to showcase

---

website/src/react-native/showcase.js

Add 'Feline for Product Hunt' into Showcase Apps

---

Libraries/Components/TextInput/TextInput.js

Reverts facebook/react-native#5354
Wasn't supposed to merge directly

Revert "TextInput should call blur and focus methods of selectionState"

---

website/src/react-native/showcase.js

CaratLane app is using react-native in HomePage. We recently went live in react-native and happy to share this news with the community.
CaratLane is one of the leading online jewellery company.

Adding CaratLane app to react-native showcase

---

website/src/react-native/showcase.js

Added reference to Bhagavad Gita Lite, built in React Native, to the showcase page. Thank you!

Add new app to showcase.html page

---

website/src/react-native/showcase.js

iOS application listed. Released Android version.

Add LoadDocs android app to showcase

---

ReactAndroid/src/main/android_res/android/support/v7/appcompat-orig/BUCK
ReactAndroid/src/main/third-party/android/support/v7/appcompat-orig/BUCK

Hey there and thanks for submitting a pull request! Please have a look at the following checklist so that others have enough information to review your pull request:
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Example: When saying "Add a function to do X", explain why it is necessary to have a way to do X.
**Test plan (required)**
Describe exact steps you've done to test that the code works. This means exact commands you ran, screenshots / videos if the pull request changes UI.
Make sure tests pass on Circle CI.
**Code formatting**
See the simple [style guide](https://github.com/facebook/react-native/blob/master/CONTRIBUTING.md#style-guide).

manual sync for D2949054

---

docs/Props.md

Summary: 
Better for doc examples
Original commit: https://github.com/facebook/react-native/commit/6b2a49e73e52bf40ab82f792e7748aa36847c17f

Cherry-pick in 0.29: Specify width and height for Image(remote source)

---

Libraries/Image/Image.ios.js

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:
> **Unless you are a React Native release maintainer and cherry-picking an *existing* commit into a current release, ensure your pull request is targeting the `master` React Native branch.**
(You can skip this if you're fixing a typo or adding an app to the Showcase.)
Explain the **motivation** for making this change. What existing problem does the pull request solve?
The spelling was incorrect in the past.
Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise please split it.
**Test plan (required)**
N/A
Demonstrate the code is solid. Example: The exact commands you ran and their …

fix spelling of example  in Image.ios.js

---

docs/Debugging.md

Minor clarity and styling improvements for Debugging.md for the "Stetho" section
No test changes required.

Minor doc improvements in Debugging.md

---

react.gradle

Fixes https://github.com/facebook/react-native/issues/25693
[Android] [Fixed] - Create source maps with the correct name and reference
Run `./gradlew assembleRelease --stacktrace` in the `android` folder and check output `android/app/build/generated/assets/react/release/index.android.bundle`

Output correct source map path if Hermes not enabled

---

template/_gitignore

The workspace file is file to be added to git. Consider it as a lockfile for native ios :)
[iOS] [Changed] - Remove the workspace from .gitignore

Removing the workspace

---

Libraries/Components/View/ReactNativeViewViewConfig.js
RNTester/js/examples/Transform/TransformExample.js
ReactAndroid/src/main/java/com/facebook/react/shell/MainReactPackage.java
scripts/test-manual-e2e.sh

The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.

Re-sync with internal repository

---

ReactCommon/jsi/jsi/test/testlib.cpp
template/metro.config.js

fbshipit-source-id: 65e2766a6a097eca0e0d0fda8dadf6871e9276c2

Re-sync with internal

---

scripts/react_native_pods.rb

[Breaking][Changed] - Pin Hermes to 0.8.0 in the react_native_pods.rb script
CircleCI

Pin hermes-engine to 0.8.x for RN 0.65

---

package.json
packages/rn-tester/Podfile.lock
scripts/react_native_pods.rb
yarn.lock

Flipper from 0.91 to 0.93 : facebook/react-native@848d599
Bump hermes to 0.8.1
https://github.com/react-native-community/releases/issues/235

Bump Flipper + Bump hermes

---

yarn.lock

Update `yarn.lock` to include the `react-native-gradle-plugin` version specified in the `package.json`.
[Internal] - Update yarn.lock with the new react-native-gradle-plugin version

Update yarn.lock with the new react-native-gradle-plugin version

---

package.json
yarn.lock

Related to https://github.com/reactwg/react-native-releases/discussions/79#discussioncomment-6467448
[ANDROID] [FIXED] - Bumped the CLI to 9.3.4 to address backward compatibility issues

fix: bumped CLI to address broken backward compatibility

---

.circleci/config.yml
Gemfile.lock
packages/rn-tester/Gemfile
scripts/update_podfile_lock.sh

Fix CI for 0.71-stable branch
[iOS][Changed] - Set the proper dependencies for iOS
CI is green

cipolleschi/fix CI

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

Updates CLI to v12.2.0 on the 0.73 branch.
[GENERAL] [CHANGED] - Bump CLI to 12.2.0
CI green

Bump CLI to 12.2.0

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

Updates the RN CLI to v12.2.1.
[GENERAL] [CHANGED] - Bump CLI to v12.2.1
CI

Bump CLI to 12.2.1

---

package.json
yarn.lock

Backports the PR https://github.com/facebook/react-native/pull/41316
[GENERAL] [CHANGED] - Bump CLI to v9.3.5
CI

BUMP CLI to v9.3.5

---

package.json
yarn.lock

Backports the PR https://github.com/facebook/react-native/pull/41316
[GENERAL] [CHANGED] - Bump CLI to v10.2.6
CI

Bump CLI to v10.2.6

---

packages/rn-tester/Podfile.lock

Bumping Hermes-engine for 0.70 to have green CI
[Internal] - Bump hermes-engine

[Local] Bump hermes-engine

---

package.json
repo-config/package.json
yarn.lock

Align package versions by running `yarn align-package-versions`
[GENERAL] [CHANGED] - Align package versions
CI

chore: align package versions

---

Libraries/LogBox/Data/LogBoxData.js
Libraries/promiseRejectionTrackingOptions.js

Apply stack Symbolication patch part 1 & 2 to 0.71-stable (https://github.com/facebook/react-native/pull/41377) (https://github.com/facebook/react-native/pull/42079) (original https://github.com/facebook/react-native/pull/40914)
This "cherry picked" PR is redone and should retain the old flow type compatibility (across 0.71-stable) which is currently different from main.
LogBox shows improvement in stack trace for custom errors.
Same as previous test plans (https://github.com/facebook/react-native/pull/41377) (https://github.com/facebook/react-native/pull/42079) (original https://github.com/facebook/react-native/pull/40914)

Apply stack Symbolication patch part 1 & 2 to 0.71-stable (#41377) (#42079) (original #40914)

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

Bump CLI version to 12.3.2
[GENERAL] [CHANGED] - Bump CLI to 12.3.2
CI

Bump CLI to 12.3.2

---

.circleci/config.yml
sdks/hermes-engine/utils/build-apple-framework.sh

Backports the commit https://github.com/facebook/react-native/commit/de6bfec82a1cb4b387bfe8a87b1f597f39572764 to 0.71
[iOS][Changed] - Disabled bitcode for Hermes prebuilts
CircleCI

[RN][iOS] Disable bitcode for Hermes

---

packages/react-native/package.json
yarn.lock

Bump CLI version to 11.4.1
[GENERAL] [CHANGED] - Bump CLI to 11.4.1
CI

Upgrade CLI to 11.4.1

---

package.json
yarn.lock

Bump CLI version to 10.2.7
[GENERAL] [CHANGED] - Bump CLI to 10.2.7
CI

Update CLI to 10.2.7

---

packages/community-cli-plugin/package.json
packages/react-native/package.json
yarn.lock

Updates CLI to 13.6.2
[GENERAL] [CHANGED] - Update `@react-native-community/cli` to 13.6.2
CI

Update `@react-native-community/cli` to 13.6.2

---

packages/react-native/template/ios/HelloWorld.xcodeproj/project.pbxproj
packages/react-native/template/ios/HelloWorld/PrivacyInfo.xcprivacy

Picks https://github.com/facebook/react-native/pull/42978
[iOS][Added] - add privacy manifest to hello world template
Run test on RNTestProject as part of release testing

add privacy manifest to hello world template

---

.circleci/configurations/executors.yml
.circleci/configurations/jobs.yml
.circleci/configurations/top_level.yml

Fix the CI build for XROS
[Internal] - Fix XROS build
CCI is green

[RN][0.74]Fix XROS build

---

.github/workflow-scripts/__tests__/publishTemplate-test.js
.github/workflow-scripts/publishTemplate.js
.github/workflow-scripts/utils.js

Local commit to fix the publishing of the template in 0.76.
We will have to backport it to main if it works
[Internal] - Fix in publishing infra
GHA

[LOCAL] Fix template publishing

---

.github/workflow-scripts/publishTemplate.js

The publishTemplate script references a variable that is not defined.
[Internal] -
GHA

[RN][Releases] Fix Publish template

---

.github/workflows/create-draft-release.yml

This change fixes a syntax error in the GH Action that generates the draft PR.
[Internal] - Fix draft release generation
GHA

[RN][Releases] Fix draft creation

---

.github/workflows/prebuild-ios-core.yml
packages/rn-tester/Podfile.lock

This PR should fix the build in CI for stable releases of RN prebuilds
[Internal] - 
GHA

[RN][CI]Fix prebuilds for stable releases
